// @generated by buffa-codegen. DO NOT EDIT.
// source: anapaya/edgetun/v1/control_service.proto

/// Request data plane configuration from the edge-tun server.
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct GetDataPlaneConfigurationRequest {}
impl ::core::fmt::Debug for GetDataPlaneConfigurationRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("GetDataPlaneConfigurationRequest").finish()
    }
}
impl GetDataPlaneConfigurationRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.GetDataPlaneConfigurationRequest";
}
::buffa::impl_default_instance!(GetDataPlaneConfigurationRequest);
impl ::buffa::MessageName for GetDataPlaneConfigurationRequest {
    const PACKAGE: &'static str = "anapaya.edgetun.v1";
    const NAME: &'static str = "GetDataPlaneConfigurationRequest";
    const FULL_NAME: &'static str = "anapaya.edgetun.v1.GetDataPlaneConfigurationRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.GetDataPlaneConfigurationRequest";
}
impl ::buffa::Message for GetDataPlaneConfigurationRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let size = 0u32;
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        _buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {}
}
impl ::buffa::json_helpers::ProtoElemJson for GetDataPlaneConfigurationRequest {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __GET_DATA_PLANE_CONFIGURATION_REQUEST_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/anapaya.edgetun.v1.GetDataPlaneConfigurationRequest",
    to_json: ::buffa::type_registry::any_to_json::<GetDataPlaneConfigurationRequest>,
    from_json: ::buffa::type_registry::any_from_json::<GetDataPlaneConfigurationRequest>,
    is_wkt: false,
};
/// Response containing data plane configuration.
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct GetDataPlaneConfigurationResponse {
    /// This address should be used for all further control plane requests.
    ///
    /// Example: "64-2:0:9b,\[2001:db8:1234:5678::42\]:5001"
    ///
    /// Field 1: `control_plane_scion_sockaddr`
    #[serde(
        rename = "controlPlaneScionSockaddr",
        alias = "control_plane_scion_sockaddr",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub control_plane_scion_sockaddr: ::buffa::alloc::string::String,
    /// The scion endhost socket address of the dataplane.
    /// Example: "64-2:0:9b,\[2001:db8:1234:5678::42\]:8000"
    ///
    /// Field 2: `data_plane_scion_sockaddr`
    #[serde(
        rename = "dataPlaneScionSockaddr",
        alias = "data_plane_scion_sockaddr",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub data_plane_scion_sockaddr: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for GetDataPlaneConfigurationResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("GetDataPlaneConfigurationResponse")
            .field("control_plane_scion_sockaddr", &self.control_plane_scion_sockaddr)
            .field("data_plane_scion_sockaddr", &self.data_plane_scion_sockaddr)
            .finish()
    }
}
impl GetDataPlaneConfigurationResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.GetDataPlaneConfigurationResponse";
}
::buffa::impl_default_instance!(GetDataPlaneConfigurationResponse);
impl ::buffa::MessageName for GetDataPlaneConfigurationResponse {
    const PACKAGE: &'static str = "anapaya.edgetun.v1";
    const NAME: &'static str = "GetDataPlaneConfigurationResponse";
    const FULL_NAME: &'static str = "anapaya.edgetun.v1.GetDataPlaneConfigurationResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.GetDataPlaneConfigurationResponse";
}
impl ::buffa::Message for GetDataPlaneConfigurationResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.control_plane_scion_sockaddr.is_empty() {
            size
                += 1u32
                    + ::buffa::types::string_encoded_len(
                        &self.control_plane_scion_sockaddr,
                    ) as u32;
        }
        if !self.data_plane_scion_sockaddr.is_empty() {
            size
                += 1u32
                    + ::buffa::types::string_encoded_len(&self.data_plane_scion_sockaddr)
                        as u32;
        }
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.control_plane_scion_sockaddr.is_empty() {
            ::buffa::types::put_string_field(
                1u32,
                &self.control_plane_scion_sockaddr,
                buf,
            );
        }
        if !self.data_plane_scion_sockaddr.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.data_plane_scion_sockaddr, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(
                    &mut self.control_plane_scion_sockaddr,
                    buf,
                )?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.data_plane_scion_sockaddr, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.control_plane_scion_sockaddr.clear();
        self.data_plane_scion_sockaddr.clear();
    }
}
impl ::buffa::json_helpers::ProtoElemJson for GetDataPlaneConfigurationResponse {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __GET_DATA_PLANE_CONFIGURATION_RESPONSE_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/anapaya.edgetun.v1.GetDataPlaneConfigurationResponse",
    to_json: ::buffa::type_registry::any_to_json::<GetDataPlaneConfigurationResponse>,
    from_json: ::buffa::type_registry::any_from_json::<
        GetDataPlaneConfigurationResponse,
    >,
    is_wkt: false,
};
/// Request to register a static identity for an edgetun connection.
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct RegisterEdgeTunIdentityRequest {
    /// The static public key of the client.
    ///
    /// Field 1: `initiator_static_x25519`
    #[serde(
        rename = "initiatorStaticX25519",
        alias = "initiator_static_x25519",
        with = "::buffa::json_helpers::bytes",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_bytes"
    )]
    pub initiator_static_x25519: ::buffa::alloc::vec::Vec<u8>,
    /// The client's pre-shared key. This can be either 32 bytes or all 0 bytes.
    ///
    /// Field 2: `psk_share`
    #[serde(
        rename = "pskShare",
        alias = "psk_share",
        with = "::buffa::json_helpers::bytes",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_bytes"
    )]
    pub psk_share: ::buffa::alloc::vec::Vec<u8>,
}
impl ::core::fmt::Debug for RegisterEdgeTunIdentityRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("RegisterEdgeTunIdentityRequest")
            .field("initiator_static_x25519", &self.initiator_static_x25519)
            .field("psk_share", &self.psk_share)
            .finish()
    }
}
impl RegisterEdgeTunIdentityRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.RegisterEdgeTunIdentityRequest";
}
::buffa::impl_default_instance!(RegisterEdgeTunIdentityRequest);
impl ::buffa::MessageName for RegisterEdgeTunIdentityRequest {
    const PACKAGE: &'static str = "anapaya.edgetun.v1";
    const NAME: &'static str = "RegisterEdgeTunIdentityRequest";
    const FULL_NAME: &'static str = "anapaya.edgetun.v1.RegisterEdgeTunIdentityRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.RegisterEdgeTunIdentityRequest";
}
impl ::buffa::Message for RegisterEdgeTunIdentityRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.initiator_static_x25519.is_empty() {
            size
                += 1u32
                    + ::buffa::types::bytes_encoded_len(&self.initiator_static_x25519)
                        as u32;
        }
        if !self.psk_share.is_empty() {
            size += 1u32 + ::buffa::types::bytes_encoded_len(&self.psk_share) as u32;
        }
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.initiator_static_x25519.is_empty() {
            ::buffa::types::put_bytes_field(1u32, &self.initiator_static_x25519, buf);
        }
        if !self.psk_share.is_empty() {
            ::buffa::types::put_bytes_field(2u32, &self.psk_share, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.initiator_static_x25519, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.psk_share, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.initiator_static_x25519.clear();
        self.psk_share.clear();
    }
}
impl ::buffa::json_helpers::ProtoElemJson for RegisterEdgeTunIdentityRequest {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __REGISTER_EDGE_TUN_IDENTITY_REQUEST_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/anapaya.edgetun.v1.RegisterEdgeTunIdentityRequest",
    to_json: ::buffa::type_registry::any_to_json::<RegisterEdgeTunIdentityRequest>,
    from_json: ::buffa::type_registry::any_from_json::<RegisterEdgeTunIdentityRequest>,
    is_wkt: false,
};
/// Response to a static identity registration request.
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct RegisterEdgeTunIdentityResponse {
    /// The static public key of the server.
    ///
    /// Field 1: `responder_static_x25519`
    #[serde(
        rename = "responderStaticX25519",
        alias = "responder_static_x25519",
        with = "::buffa::json_helpers::bytes",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_bytes"
    )]
    pub responder_static_x25519: ::buffa::alloc::vec::Vec<u8>,
    /// The server's pre-shared key. This can be either 32 bytes or all 0 bytes.
    ///
    /// Field 2: `psk_share`
    #[serde(
        rename = "pskShare",
        alias = "psk_share",
        with = "::buffa::json_helpers::bytes",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_bytes"
    )]
    pub psk_share: ::buffa::alloc::vec::Vec<u8>,
}
impl ::core::fmt::Debug for RegisterEdgeTunIdentityResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("RegisterEdgeTunIdentityResponse")
            .field("responder_static_x25519", &self.responder_static_x25519)
            .field("psk_share", &self.psk_share)
            .finish()
    }
}
impl RegisterEdgeTunIdentityResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.RegisterEdgeTunIdentityResponse";
}
::buffa::impl_default_instance!(RegisterEdgeTunIdentityResponse);
impl ::buffa::MessageName for RegisterEdgeTunIdentityResponse {
    const PACKAGE: &'static str = "anapaya.edgetun.v1";
    const NAME: &'static str = "RegisterEdgeTunIdentityResponse";
    const FULL_NAME: &'static str = "anapaya.edgetun.v1.RegisterEdgeTunIdentityResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.RegisterEdgeTunIdentityResponse";
}
impl ::buffa::Message for RegisterEdgeTunIdentityResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.responder_static_x25519.is_empty() {
            size
                += 1u32
                    + ::buffa::types::bytes_encoded_len(&self.responder_static_x25519)
                        as u32;
        }
        if !self.psk_share.is_empty() {
            size += 1u32 + ::buffa::types::bytes_encoded_len(&self.psk_share) as u32;
        }
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.responder_static_x25519.is_empty() {
            ::buffa::types::put_bytes_field(1u32, &self.responder_static_x25519, buf);
        }
        if !self.psk_share.is_empty() {
            ::buffa::types::put_bytes_field(2u32, &self.psk_share, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.responder_static_x25519, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.psk_share, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.responder_static_x25519.clear();
        self.psk_share.clear();
    }
}
impl ::buffa::json_helpers::ProtoElemJson for RegisterEdgeTunIdentityResponse {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __REGISTER_EDGE_TUN_IDENTITY_RESPONSE_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/anapaya.edgetun.v1.RegisterEdgeTunIdentityResponse",
    to_json: ::buffa::type_registry::any_to_json::<RegisterEdgeTunIdentityResponse>,
    from_json: ::buffa::type_registry::any_from_json::<RegisterEdgeTunIdentityResponse>,
    is_wkt: false,
};
/// Request to assign IP addresses.
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct AddressAssignRequest {
    /// Client's static identity.
    ///
    /// Field 1: `client_identity`
    #[serde(
        rename = "clientIdentity",
        alias = "client_identity",
        with = "::buffa::json_helpers::bytes",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_bytes"
    )]
    pub client_identity: ::buffa::alloc::vec::Vec<u8>,
    /// The requested IP address ranges.
    ///
    /// Field 2: `requested_addresses`
    #[serde(
        rename = "requestedAddresses",
        alias = "requested_addresses",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_vec",
        deserialize_with = "::buffa::json_helpers::null_as_default"
    )]
    pub requested_addresses: ::buffa::alloc::vec::Vec<IpAddressRange>,
}
impl ::core::fmt::Debug for AddressAssignRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("AddressAssignRequest")
            .field("client_identity", &self.client_identity)
            .field("requested_addresses", &self.requested_addresses)
            .finish()
    }
}
impl AddressAssignRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.AddressAssignRequest";
}
::buffa::impl_default_instance!(AddressAssignRequest);
impl ::buffa::MessageName for AddressAssignRequest {
    const PACKAGE: &'static str = "anapaya.edgetun.v1";
    const NAME: &'static str = "AddressAssignRequest";
    const FULL_NAME: &'static str = "anapaya.edgetun.v1.AddressAssignRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.AddressAssignRequest";
}
impl ::buffa::Message for AddressAssignRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.client_identity.is_empty() {
            size
                += 1u32
                    + ::buffa::types::bytes_encoded_len(&self.client_identity) as u32;
        }
        for v in &self.requested_addresses {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        size
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.client_identity.is_empty() {
            ::buffa::types::put_bytes_field(1u32, &self.client_identity, buf);
        }
        for v in &self.requested_addresses {
            ::buffa::types::put_len_delimited_header(2u32, __cache.consume_next(), buf);
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.client_identity, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.requested_addresses.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.client_identity.clear();
        self.requested_addresses.clear();
    }
}
impl ::buffa::json_helpers::ProtoElemJson for AddressAssignRequest {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __ADDRESS_ASSIGN_REQUEST_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/anapaya.edgetun.v1.AddressAssignRequest",
    to_json: ::buffa::type_registry::any_to_json::<AddressAssignRequest>,
    from_json: ::buffa::type_registry::any_from_json::<AddressAssignRequest>,
    is_wkt: false,
};
/// Response containing assigned IP address ranges.
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct AddressAssignResponse {
    /// The assigned address ranges.
    ///
    /// Field 1: `assigned_addresses`
    #[serde(
        rename = "assignedAddresses",
        alias = "assigned_addresses",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_vec",
        deserialize_with = "::buffa::json_helpers::null_as_default"
    )]
    pub assigned_addresses: ::buffa::alloc::vec::Vec<IpAddressRange>,
}
impl ::core::fmt::Debug for AddressAssignResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("AddressAssignResponse")
            .field("assigned_addresses", &self.assigned_addresses)
            .finish()
    }
}
impl AddressAssignResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.AddressAssignResponse";
}
::buffa::impl_default_instance!(AddressAssignResponse);
impl ::buffa::MessageName for AddressAssignResponse {
    const PACKAGE: &'static str = "anapaya.edgetun.v1";
    const NAME: &'static str = "AddressAssignResponse";
    const FULL_NAME: &'static str = "anapaya.edgetun.v1.AddressAssignResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.AddressAssignResponse";
}
impl ::buffa::Message for AddressAssignResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        for v in &self.assigned_addresses {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        size
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.assigned_addresses {
            ::buffa::types::put_len_delimited_header(1u32, __cache.consume_next(), buf);
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.assigned_addresses.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.assigned_addresses.clear();
    }
}
impl ::buffa::json_helpers::ProtoElemJson for AddressAssignResponse {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __ADDRESS_ASSIGN_RESPONSE_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/anapaya.edgetun.v1.AddressAssignResponse",
    to_json: ::buffa::type_registry::any_to_json::<AddressAssignResponse>,
    from_json: ::buffa::type_registry::any_from_json::<AddressAssignResponse>,
    is_wkt: false,
};
/// Request advertised routes from the edge-tun server.
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct GetRouteAdvertisementRequest {
    /// Client's static identity.
    ///
    /// Field 1: `client_identity`
    #[serde(
        rename = "clientIdentity",
        alias = "client_identity",
        with = "::buffa::json_helpers::bytes",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_bytes"
    )]
    pub client_identity: ::buffa::alloc::vec::Vec<u8>,
}
impl ::core::fmt::Debug for GetRouteAdvertisementRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("GetRouteAdvertisementRequest")
            .field("client_identity", &self.client_identity)
            .finish()
    }
}
impl GetRouteAdvertisementRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.GetRouteAdvertisementRequest";
}
::buffa::impl_default_instance!(GetRouteAdvertisementRequest);
impl ::buffa::MessageName for GetRouteAdvertisementRequest {
    const PACKAGE: &'static str = "anapaya.edgetun.v1";
    const NAME: &'static str = "GetRouteAdvertisementRequest";
    const FULL_NAME: &'static str = "anapaya.edgetun.v1.GetRouteAdvertisementRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.GetRouteAdvertisementRequest";
}
impl ::buffa::Message for GetRouteAdvertisementRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.client_identity.is_empty() {
            size
                += 1u32
                    + ::buffa::types::bytes_encoded_len(&self.client_identity) as u32;
        }
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.client_identity.is_empty() {
            ::buffa::types::put_bytes_field(1u32, &self.client_identity, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.client_identity, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.client_identity.clear();
    }
}
impl ::buffa::json_helpers::ProtoElemJson for GetRouteAdvertisementRequest {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __GET_ROUTE_ADVERTISEMENT_REQUEST_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/anapaya.edgetun.v1.GetRouteAdvertisementRequest",
    to_json: ::buffa::type_registry::any_to_json::<GetRouteAdvertisementRequest>,
    from_json: ::buffa::type_registry::any_from_json::<GetRouteAdvertisementRequest>,
    is_wkt: false,
};
/// Response containing advertised routes.
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct GetRouteAdvertisementResponse {
    /// The list of advertised routes.
    ///
    /// Field 1: `route`
    #[serde(
        rename = "route",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_vec",
        deserialize_with = "::buffa::json_helpers::null_as_default"
    )]
    pub route: ::buffa::alloc::vec::Vec<IpAddressRange>,
}
impl ::core::fmt::Debug for GetRouteAdvertisementResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("GetRouteAdvertisementResponse")
            .field("route", &self.route)
            .finish()
    }
}
impl GetRouteAdvertisementResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.GetRouteAdvertisementResponse";
}
::buffa::impl_default_instance!(GetRouteAdvertisementResponse);
impl ::buffa::MessageName for GetRouteAdvertisementResponse {
    const PACKAGE: &'static str = "anapaya.edgetun.v1";
    const NAME: &'static str = "GetRouteAdvertisementResponse";
    const FULL_NAME: &'static str = "anapaya.edgetun.v1.GetRouteAdvertisementResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.GetRouteAdvertisementResponse";
}
impl ::buffa::Message for GetRouteAdvertisementResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        for v in &self.route {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        size
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.route {
            ::buffa::types::put_len_delimited_header(1u32, __cache.consume_next(), buf);
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.route.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.route.clear();
    }
}
impl ::buffa::json_helpers::ProtoElemJson for GetRouteAdvertisementResponse {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __GET_ROUTE_ADVERTISEMENT_RESPONSE_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/anapaya.edgetun.v1.GetRouteAdvertisementResponse",
    to_json: ::buffa::type_registry::any_to_json::<GetRouteAdvertisementResponse>,
    from_json: ::buffa::type_registry::any_from_json::<GetRouteAdvertisementResponse>,
    is_wkt: false,
};
/// An IP address range represented as network prefix.
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct IpAddressRange {
    /// Version MUST be either 4 or 6, indicating IPv4 or IPv6 respectively.
    ///
    /// Field 1: `version`
    #[serde(
        rename = "version",
        with = "::buffa::json_helpers::uint32",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_u32"
    )]
    pub version: u32,
    /// The length of the network prefix. May not be larger than 32
    /// for version = 4, and may not be larger than 128 for version = 6.
    ///
    /// Field 2: `prefix_length`
    #[serde(
        rename = "prefixLength",
        alias = "prefix_length",
        with = "::buffa::json_helpers::uint32",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_u32"
    )]
    pub prefix_length: u32,
    /// The IP address in network format. The length of the address
    /// must be 4 for version = 4 and 16 for version = 6.
    ///
    /// Field 3: `address`
    #[serde(
        rename = "address",
        with = "::buffa::json_helpers::bytes",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_bytes"
    )]
    pub address: ::buffa::alloc::vec::Vec<u8>,
}
impl ::core::fmt::Debug for IpAddressRange {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("IpAddressRange")
            .field("version", &self.version)
            .field("prefix_length", &self.prefix_length)
            .field("address", &self.address)
            .finish()
    }
}
impl IpAddressRange {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.IpAddressRange";
}
::buffa::impl_default_instance!(IpAddressRange);
impl ::buffa::MessageName for IpAddressRange {
    const PACKAGE: &'static str = "anapaya.edgetun.v1";
    const NAME: &'static str = "IpAddressRange";
    const FULL_NAME: &'static str = "anapaya.edgetun.v1.IpAddressRange";
    const TYPE_URL: &'static str = "type.googleapis.com/anapaya.edgetun.v1.IpAddressRange";
}
impl ::buffa::Message for IpAddressRange {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.version != 0u32 {
            size += 1u32 + ::buffa::types::uint32_encoded_len(self.version) as u32;
        }
        if self.prefix_length != 0u32 {
            size += 1u32 + ::buffa::types::uint32_encoded_len(self.prefix_length) as u32;
        }
        if !self.address.is_empty() {
            size += 1u32 + ::buffa::types::bytes_encoded_len(&self.address) as u32;
        }
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.version != 0u32 {
            ::buffa::types::put_uint32_field(1u32, self.version, buf);
        }
        if self.prefix_length != 0u32 {
            ::buffa::types::put_uint32_field(2u32, self.prefix_length, buf);
        }
        if !self.address.is_empty() {
            ::buffa::types::put_bytes_field(3u32, &self.address, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.version = ::buffa::types::decode_uint32(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.prefix_length = ::buffa::types::decode_uint32(buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.address, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.version = 0u32;
        self.prefix_length = 0u32;
        self.address.clear();
    }
}
impl ::buffa::json_helpers::ProtoElemJson for IpAddressRange {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __IP_ADDRESS_RANGE_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/anapaya.edgetun.v1.IpAddressRange",
    to_json: ::buffa::type_registry::any_to_json::<IpAddressRange>,
    from_json: ::buffa::type_registry::any_from_json::<IpAddressRange>,
    is_wkt: false,
};
