// @generated by buffa-codegen. DO NOT EDIT.

include!("anapaya.edgetun.v1.control_service.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("anapaya.edgetun.v1.control_service.__view.rs");
    }
    /// Register this package's `Any` type entries and extension entries.
    pub fn register_types(reg: &mut ::buffa::type_registry::TypeRegistry) {
        reg.register_json_any(super::__GET_DATA_PLANE_CONFIGURATION_REQUEST_JSON_ANY);
        reg.register_json_any(super::__GET_DATA_PLANE_CONFIGURATION_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__REGISTER_EDGE_TUN_IDENTITY_REQUEST_JSON_ANY);
        reg.register_json_any(super::__REGISTER_EDGE_TUN_IDENTITY_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__ADDRESS_ASSIGN_REQUEST_JSON_ANY);
        reg.register_json_any(super::__ADDRESS_ASSIGN_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__GET_ROUTE_ADVERTISEMENT_REQUEST_JSON_ANY);
        reg.register_json_any(super::__GET_ROUTE_ADVERTISEMENT_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__IP_ADDRESS_RANGE_JSON_ANY);
    }
}
#[doc(inline)]
pub use self::__buffa::view::GetDataPlaneConfigurationRequestView;
#[doc(inline)]
pub use self::__buffa::view::GetDataPlaneConfigurationRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::GetDataPlaneConfigurationResponseView;
#[doc(inline)]
pub use self::__buffa::view::GetDataPlaneConfigurationResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::RegisterEdgeTunIdentityRequestView;
#[doc(inline)]
pub use self::__buffa::view::RegisterEdgeTunIdentityRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::RegisterEdgeTunIdentityResponseView;
#[doc(inline)]
pub use self::__buffa::view::RegisterEdgeTunIdentityResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::AddressAssignRequestView;
#[doc(inline)]
pub use self::__buffa::view::AddressAssignRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::AddressAssignResponseView;
#[doc(inline)]
pub use self::__buffa::view::AddressAssignResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::GetRouteAdvertisementRequestView;
#[doc(inline)]
pub use self::__buffa::view::GetRouteAdvertisementRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::GetRouteAdvertisementResponseView;
#[doc(inline)]
pub use self::__buffa::view::GetRouteAdvertisementResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::IpAddressRangeView;
#[doc(inline)]
pub use self::__buffa::view::IpAddressRangeOwnedView;
#[doc(inline)]
pub use self::__buffa::register_types;
