// @generated by buffa-codegen. DO NOT EDIT.

include!("anapaya.aa.v1.auth_service.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("anapaya.aa.v1.auth_service.__view.rs");
    }
    /// Register this package's `Any` type entries and extension entries.
    pub fn register_types(reg: &mut ::buffa::type_registry::TypeRegistry) {
        reg.register_json_any(super::__AUTHENTICATE_BY_KEY_REQUEST_JSON_ANY);
        reg.register_json_any(super::__METADATA_JSON_ANY);
        reg.register_json_any(super::__AUTHENTICATE_BY_KEY_RESPONSE_JSON_ANY);
    }
}
#[doc(inline)]
pub use self::__buffa::view::AuthenticateByKeyRequestView;
#[doc(inline)]
pub use self::__buffa::view::AuthenticateByKeyRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::MetadataView;
#[doc(inline)]
pub use self::__buffa::view::MetadataOwnedView;
#[doc(inline)]
pub use self::__buffa::view::AuthenticateByKeyResponseView;
#[doc(inline)]
pub use self::__buffa::view::AuthenticateByKeyResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::register_types;
