[package]
name = "anapaya-aa-protobuf"
version = "0.8.0"
edition.workspace = true
authors = ["Anapaya & contributors"]
license = "Apache-2.0"
description = "Protobuf definitions for the Anapaya AA (Auth/n Auth/z) service"
repository = "https://github.com/anapaya/scion-sdk"
keywords = ["SCION", "networking", "Anapaya"]

[dependencies]
buffa = { workspace = true, features = ["json"] }
serde = { workspace = true }

[lints]
workspace = true
