// This file is @generated by prost-build.
/// Request to authenticate a client by API key.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthenticateByKeyRequest {
    /// The raw API key secret (prefixed with "aakey\_").
    #[prost(string, tag = "1")]
    pub api_key: ::prost::alloc::string::String,
    /// Client-supplied device identifier.
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    /// Requested token TTL in seconds. 0 means "use the default" (3600).
    /// Values below 900 and above 86400 are clamped to the nearest boundary.
    #[prost(int32, tag = "3")]
    pub requested_validity: i32,
}
/// Metadata returned alongside the authentication response.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Metadata {
    /// URL of the endhost API discovery service scoped to the authenticated user.
    /// When present and non-empty, the client should use this URL to discover
    /// authorised endhost APIs instead of the global discovery service at
    /// <https://discovery.scion.anapaya.net.>
    #[prost(string, optional, tag = "1")]
    pub endhost_api_discovery_url: ::core::option::Option<
        ::prost::alloc::string::String,
    >,
}
/// Response containing the signed SNAP token.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthenticateByKeyResponse {
    /// The signed JWT SNAP token.
    #[prost(string, tag = "1")]
    pub snap_token: ::prost::alloc::string::String,
    /// Optional metadata provided by the AA service.
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<Metadata>,
}
