[package]
name = "scion-protobuf"
version = "0.7.0"
edition.workspace = true
authors = ["Anapaya & contributors"]
license = "Apache-2.0"
description = "Protobuf definitions used in the SCION control plane"
repository = "https://github.com/anapaya/scion-sdk"
keywords = ["SCION", "networking"]
categories = ["network-programming"]

[lib]
bench = false

[dependencies]
buffa = { workspace = true, features = ["json"] }
buffa-types = { workspace = true }
connectrpc = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
