// @generated by buffa-codegen. DO NOT EDIT.
// source: endhost/discovery/v1/discovery_service.proto

/// Request to discovery available Endhost APIs.
#[derive(Clone, Debug, Default)]
pub struct RpcGetEndhostApisRequestView<'a> {
    #[doc(hidden)]
    pub __buffa_phantom: ::core::marker::PhantomData<&'a ()>,
}
impl<'a> ::buffa::MessageView<'a> for RpcGetEndhostApisRequestView<'a> {
    type Owned = super::super::RpcGetEndhostApisRequest;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::RpcGetEndhostApisRequest,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::RpcGetEndhostApisRequest,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::RpcGetEndhostApisRequest {
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for RpcGetEndhostApisRequestView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let size = 0u32;
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        _buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for RpcGetEndhostApisRequestView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for RpcGetEndhostApisRequestView<'a> {
    const PACKAGE: &'static str = "endhost.discovery.v1";
    const NAME: &'static str = "RpcGetEndhostApisRequest";
    const FULL_NAME: &'static str = "endhost.discovery.v1.RpcGetEndhostApisRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/endhost.discovery.v1.RpcGetEndhostApisRequest";
}
::buffa::impl_default_view_instance!(RpcGetEndhostApisRequestView);
::buffa::impl_view_reborrow!(RpcGetEndhostApisRequestView);
/** Self-contained, `'static` owned view of a `RpcGetEndhostApisRequest` message.

 Wraps [`::buffa::OwnedView`]`<`[`RpcGetEndhostApisRequestView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`RpcGetEndhostApisRequestView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct RpcGetEndhostApisRequestOwnedView(
    ::buffa::OwnedView<RpcGetEndhostApisRequestView<'static>>,
);
impl RpcGetEndhostApisRequestOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetEndhostApisRequestOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetEndhostApisRequestOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::RpcGetEndhostApisRequest,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetEndhostApisRequestOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`RpcGetEndhostApisRequestView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &RpcGetEndhostApisRequestView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::RpcGetEndhostApisRequest,
        ::buffa::DecodeError,
    > {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
}
impl ::core::convert::From<::buffa::OwnedView<RpcGetEndhostApisRequestView<'static>>>
for RpcGetEndhostApisRequestOwnedView {
    fn from(inner: ::buffa::OwnedView<RpcGetEndhostApisRequestView<'static>>) -> Self {
        RpcGetEndhostApisRequestOwnedView(inner)
    }
}
impl ::core::convert::From<RpcGetEndhostApisRequestOwnedView>
for ::buffa::OwnedView<RpcGetEndhostApisRequestView<'static>> {
    fn from(wrapper: RpcGetEndhostApisRequestOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<RpcGetEndhostApisRequestView<'static>>>
for RpcGetEndhostApisRequestOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<RpcGetEndhostApisRequestView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::RpcGetEndhostApisRequest {
    type View<'a> = RpcGetEndhostApisRequestView<'a>;
    type ViewHandle = RpcGetEndhostApisRequestOwnedView;
}
impl ::serde::Serialize for RpcGetEndhostApisRequestOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
/// Endhost APIs response message.
#[derive(Clone, Debug, Default)]
pub struct RpcGetEndhostApisResponseView<'a> {
    /// Set of Endhost APIs groups.
    /// Should be used in order, using the first reachable one.
    ///
    /// After establishing a connection to an API in a group, the client can failover to any other API in the same group if the connection fails.
    /// Failover between groups requires the client to re-establish connections to snaps and other services using the new API.
    ///
    /// Field 1: `groups`
    pub groups: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::RpcEndhostApiGroupView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for RpcGetEndhostApisResponseView<'a> {
    type Owned = super::super::RpcGetEndhostApisResponse;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                view.groups
                    .push(
                        <super::super::__buffa::view::RpcEndhostApiGroupView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::RpcGetEndhostApisResponse,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::RpcGetEndhostApisResponse,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::RpcGetEndhostApisResponse {
            groups: self
                .groups
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for RpcGetEndhostApisResponseView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        for v in &self.groups {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.groups {
            ::buffa::types::put_len_delimited_header(1u32, __cache.consume_next(), buf);
            v.write_to(__cache, buf);
        }
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for RpcGetEndhostApisResponseView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !self.groups.is_empty() {
            __map.serialize_entry("groups", &*self.groups)?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for RpcGetEndhostApisResponseView<'a> {
    const PACKAGE: &'static str = "endhost.discovery.v1";
    const NAME: &'static str = "RpcGetEndhostApisResponse";
    const FULL_NAME: &'static str = "endhost.discovery.v1.RpcGetEndhostApisResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/endhost.discovery.v1.RpcGetEndhostApisResponse";
}
::buffa::impl_default_view_instance!(RpcGetEndhostApisResponseView);
::buffa::impl_view_reborrow!(RpcGetEndhostApisResponseView);
/** Self-contained, `'static` owned view of a `RpcGetEndhostApisResponse` message.

 Wraps [`::buffa::OwnedView`]`<`[`RpcGetEndhostApisResponseView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`RpcGetEndhostApisResponseView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct RpcGetEndhostApisResponseOwnedView(
    ::buffa::OwnedView<RpcGetEndhostApisResponseView<'static>>,
);
impl RpcGetEndhostApisResponseOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetEndhostApisResponseOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetEndhostApisResponseOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::RpcGetEndhostApisResponse,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetEndhostApisResponseOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`RpcGetEndhostApisResponseView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &RpcGetEndhostApisResponseView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::RpcGetEndhostApisResponse,
        ::buffa::DecodeError,
    > {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Set of Endhost APIs groups.
    /// Should be used in order, using the first reachable one.
    ///
    /// After establishing a connection to an API in a group, the client can failover to any other API in the same group if the connection fails.
    /// Failover between groups requires the client to re-establish connections to snaps and other services using the new API.
    ///
    /// Field 1: `groups`
    #[must_use]
    pub fn groups(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::__buffa::view::RpcEndhostApiGroupView<'_>,
    > {
        &self.0.reborrow().groups
    }
}
impl ::core::convert::From<::buffa::OwnedView<RpcGetEndhostApisResponseView<'static>>>
for RpcGetEndhostApisResponseOwnedView {
    fn from(inner: ::buffa::OwnedView<RpcGetEndhostApisResponseView<'static>>) -> Self {
        RpcGetEndhostApisResponseOwnedView(inner)
    }
}
impl ::core::convert::From<RpcGetEndhostApisResponseOwnedView>
for ::buffa::OwnedView<RpcGetEndhostApisResponseView<'static>> {
    fn from(wrapper: RpcGetEndhostApisResponseOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<RpcGetEndhostApisResponseView<'static>>>
for RpcGetEndhostApisResponseOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<RpcGetEndhostApisResponseView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::RpcGetEndhostApisResponse {
    type View<'a> = RpcGetEndhostApisResponseView<'a>;
    type ViewHandle = RpcGetEndhostApisResponseOwnedView;
}
impl ::serde::Serialize for RpcGetEndhostApisResponseOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
/// Group of Endhost APIs the client can failover between.
#[derive(Clone, Debug, Default)]
pub struct RpcEndhostApiGroupView<'a> {
    /// URL of the Endhost API.
    ///
    /// Field 1: `apis`
    pub apis: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::RpcEndhostApiInfoView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for RpcEndhostApiGroupView<'a> {
    type Owned = super::super::RpcEndhostApiGroup;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                view.apis
                    .push(
                        <super::super::__buffa::view::RpcEndhostApiInfoView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::RpcEndhostApiGroup, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::RpcEndhostApiGroup, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::RpcEndhostApiGroup {
            apis: self
                .apis
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for RpcEndhostApiGroupView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        for v in &self.apis {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.apis {
            ::buffa::types::put_len_delimited_header(1u32, __cache.consume_next(), buf);
            v.write_to(__cache, buf);
        }
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for RpcEndhostApiGroupView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !self.apis.is_empty() {
            __map.serialize_entry("apis", &*self.apis)?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for RpcEndhostApiGroupView<'a> {
    const PACKAGE: &'static str = "endhost.discovery.v1";
    const NAME: &'static str = "RpcEndhostApiGroup";
    const FULL_NAME: &'static str = "endhost.discovery.v1.RpcEndhostApiGroup";
    const TYPE_URL: &'static str = "type.googleapis.com/endhost.discovery.v1.RpcEndhostApiGroup";
}
::buffa::impl_default_view_instance!(RpcEndhostApiGroupView);
::buffa::impl_view_reborrow!(RpcEndhostApiGroupView);
/** Self-contained, `'static` owned view of a `RpcEndhostApiGroup` message.

 Wraps [`::buffa::OwnedView`]`<`[`RpcEndhostApiGroupView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`RpcEndhostApiGroupView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct RpcEndhostApiGroupOwnedView(
    ::buffa::OwnedView<RpcEndhostApiGroupView<'static>>,
);
impl RpcEndhostApiGroupOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcEndhostApiGroupOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcEndhostApiGroupOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::RpcEndhostApiGroup,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcEndhostApiGroupOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`RpcEndhostApiGroupView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &RpcEndhostApiGroupView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::RpcEndhostApiGroup, ::buffa::DecodeError> {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// URL of the Endhost API.
    ///
    /// Field 1: `apis`
    #[must_use]
    pub fn apis(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::__buffa::view::RpcEndhostApiInfoView<'_>,
    > {
        &self.0.reborrow().apis
    }
}
impl ::core::convert::From<::buffa::OwnedView<RpcEndhostApiGroupView<'static>>>
for RpcEndhostApiGroupOwnedView {
    fn from(inner: ::buffa::OwnedView<RpcEndhostApiGroupView<'static>>) -> Self {
        RpcEndhostApiGroupOwnedView(inner)
    }
}
impl ::core::convert::From<RpcEndhostApiGroupOwnedView>
for ::buffa::OwnedView<RpcEndhostApiGroupView<'static>> {
    fn from(wrapper: RpcEndhostApiGroupOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<RpcEndhostApiGroupView<'static>>>
for RpcEndhostApiGroupOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<RpcEndhostApiGroupView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::RpcEndhostApiGroup {
    type View<'a> = RpcEndhostApiGroupView<'a>;
    type ViewHandle = RpcEndhostApiGroupOwnedView;
}
impl ::serde::Serialize for RpcEndhostApiGroupOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
/// Single Endhost API.
#[derive(Clone, Debug, Default)]
pub struct RpcEndhostApiInfoView<'a> {
    /// URL of the Endhost API.
    ///
    /// Field 1: `address`
    pub address: &'a str,
}
impl<'a> ::buffa::MessageView<'a> for RpcEndhostApiInfoView<'a> {
    type Owned = super::super::RpcEndhostApiInfo;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.address = ::buffa::types::borrow_str(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::RpcEndhostApiInfo, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::RpcEndhostApiInfo, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::RpcEndhostApiInfo {
            address: self.address.to_string(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for RpcEndhostApiInfoView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.address.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.address) as u32;
        }
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.address.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.address, buf);
        }
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for RpcEndhostApiInfoView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !::buffa::json_helpers::skip_if::is_empty_str(self.address) {
            __map.serialize_entry("address", self.address)?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for RpcEndhostApiInfoView<'a> {
    const PACKAGE: &'static str = "endhost.discovery.v1";
    const NAME: &'static str = "RpcEndhostApiInfo";
    const FULL_NAME: &'static str = "endhost.discovery.v1.RpcEndhostApiInfo";
    const TYPE_URL: &'static str = "type.googleapis.com/endhost.discovery.v1.RpcEndhostApiInfo";
}
::buffa::impl_default_view_instance!(RpcEndhostApiInfoView);
::buffa::impl_view_reborrow!(RpcEndhostApiInfoView);
/** Self-contained, `'static` owned view of a `RpcEndhostApiInfo` message.

 Wraps [`::buffa::OwnedView`]`<`[`RpcEndhostApiInfoView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`RpcEndhostApiInfoView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct RpcEndhostApiInfoOwnedView(
    ::buffa::OwnedView<RpcEndhostApiInfoView<'static>>,
);
impl RpcEndhostApiInfoOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcEndhostApiInfoOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcEndhostApiInfoOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::RpcEndhostApiInfo,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcEndhostApiInfoOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`RpcEndhostApiInfoView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &RpcEndhostApiInfoView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::RpcEndhostApiInfo, ::buffa::DecodeError> {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// URL of the Endhost API.
    ///
    /// Field 1: `address`
    #[must_use]
    pub fn address(&self) -> &'_ str {
        self.0.reborrow().address
    }
}
impl ::core::convert::From<::buffa::OwnedView<RpcEndhostApiInfoView<'static>>>
for RpcEndhostApiInfoOwnedView {
    fn from(inner: ::buffa::OwnedView<RpcEndhostApiInfoView<'static>>) -> Self {
        RpcEndhostApiInfoOwnedView(inner)
    }
}
impl ::core::convert::From<RpcEndhostApiInfoOwnedView>
for ::buffa::OwnedView<RpcEndhostApiInfoView<'static>> {
    fn from(wrapper: RpcEndhostApiInfoOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<RpcEndhostApiInfoView<'static>>>
for RpcEndhostApiInfoOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<RpcEndhostApiInfoView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::RpcEndhostApiInfo {
    type View<'a> = RpcEndhostApiInfoView<'a>;
    type ViewHandle = RpcEndhostApiInfoOwnedView;
}
impl ::serde::Serialize for RpcEndhostApiInfoOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
