[package]
name = "endhost-api"
version = "0.8.0"
edition.workspace = true
authors = ["Anapaya & contributors"]
license = "Apache-2.0"
description = "SCION endhost API"
repository = "https://github.com/anapaya/scion-sdk"
keywords = ["SCION", "networking"]

[package.metadata.cargo-shear]
ignored = ["tokio", "async-trait"]

[dependencies]
axum-connect-rpc = { workspace = true }
# Local Dependencies
endhost-api-models = { workspace = true }
endhost-api-protobuf = { workspace = true }
sciparse = { workspace = true }

# Global Dependencies
axum = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true } # only used in doc-tests
tokio = { workspace = true } # only used in doc-tests

[lints]
workspace = true
