// @generated by buffa-codegen. DO NOT EDIT.

include!("anapaya.snap.v1.control_service.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("anapaya.snap.v1.control_service.__view.rs");
    }
    /// Register this package's `Any` type entries and extension entries.
    pub fn register_types(reg: &mut ::buffa::type_registry::TypeRegistry) {
        reg.register_json_any(super::__GET_SNAP_DATA_PLANE_ADDRESS_REQUEST_JSON_ANY);
        reg.register_json_any(super::__GET_SNAP_DATA_PLANE_ADDRESS_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__REGISTER_SNAP_TUN_IDENTITY_REQUEST_JSON_ANY);
        reg.register_json_any(super::__REGISTER_SNAP_TUN_IDENTITY_RESPONSE_JSON_ANY);
    }
}
#[doc(inline)]
pub use self::__buffa::view::GetSnapDataPlaneAddressRequestView;
#[doc(inline)]
pub use self::__buffa::view::GetSnapDataPlaneAddressRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::GetSnapDataPlaneAddressResponseView;
#[doc(inline)]
pub use self::__buffa::view::GetSnapDataPlaneAddressResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::RegisterSnapTunIdentityRequestView;
#[doc(inline)]
pub use self::__buffa::view::RegisterSnapTunIdentityRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::RegisterSnapTunIdentityResponseView;
#[doc(inline)]
pub use self::__buffa::view::RegisterSnapTunIdentityResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::register_types;
include!("anapaya.snap.v1.control_service.__connect.rs");
