// @generated by buffa-codegen. DO NOT EDIT.

include!("anapaya.wap.v1.control_service.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("anapaya.wap.v1.control_service.__view.rs");
    }
    /// Register this package's `Any` type entries and extension entries.
    pub fn register_types(reg: &mut ::buffa::type_registry::TypeRegistry) {
        reg.register_json_any(super::__AUTHORIZE_TARGETS_REQUEST_JSON_ANY);
        reg.register_json_any(super::__AUTH_SEGMENTS_JSON_ANY);
        reg.register_json_any(super::__AUTHORIZE_TARGETS_RESPONSE_JSON_ANY);
    }
}
#[doc(inline)]
pub use self::__buffa::view::AuthorizeTargetsRequestView;
#[doc(inline)]
pub use self::__buffa::view::AuthorizeTargetsRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::AuthSegmentsView;
#[doc(inline)]
pub use self::__buffa::view::AuthSegmentsOwnedView;
#[doc(inline)]
pub use self::__buffa::view::AuthorizeTargetsResponseView;
#[doc(inline)]
pub use self::__buffa::view::AuthorizeTargetsResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::register_types;
include!("anapaya.wap.v1.control_service.__connect.rs");
