// Copyright 2026 Anapaya Systems

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Auto-generate the sidebar from the guide markdown tree (../docs/guide).
const sidebars: SidebarsConfig = {
    guide: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
