// Copyright 2026 Anapaya Systems
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//! Connect RPC axum extractors for [`buffa`] messages.
//!
//! Same extractors as [`prost`](super::prost), for messages generated by
//! `buffa-codegen` instead of `prost`. Codec negotiation, the rejection type
//! and the error envelopes live in the parent module and are shared with the
//! prost path; only the encode/decode calls differ.

use std::fmt::Debug;

use axum::{
    extract::{FromRequest, Request},
    http::{StatusCode, header},
    response::{IntoResponse, Response},
};
use bytes::Bytes;

use super::{APPLICATION_PROTO, Codec, ConnectRpcRejection, check_crpc_content_type};
use crate::error::{CrpcError, CrpcErrorCode};

/// Wrapper connect RPC type for a buffa message.
///
/// Protobuf-only: the request must be `application/proto`, and the response is
/// encoded with the same content type. Use [`BuffaConnectRpcAny`] for a service that
/// must also answer JSON.
pub struct BuffaConnectRpc<T: ::buffa::Message>(pub T);

impl<T: ::buffa::Message> BuffaConnectRpc<T> {
    /// Extract the inner message.
    pub fn into_inner(self) -> T {
        self.0
    }
}

impl<T: ::buffa::Message + Debug> std::fmt::Debug for BuffaConnectRpc<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("ConnectRpc").field(&self.0).finish()
    }
}

impl<T: ::buffa::Message> std::ops::Deref for BuffaConnectRpc<T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl<S, T> FromRequest<S> for BuffaConnectRpc<T>
where
    S: Send + Sync,
    T: ::buffa::Message,
{
    type Rejection = ConnectRpcRejection;

    async fn from_request(req: Request, state: &S) -> Result<Self, Self::Rejection> {
        check_crpc_content_type(req.headers())?;

        let bytes = Bytes::from_request(req, state)
            .await
            .map_err(ConnectRpcRejection::BytesRejection)?;

        let message =
            T::decode_from_slice(&bytes).map_err(|_e| ConnectRpcRejection::DecodingFailed)?;

        Ok(BuffaConnectRpc(message))
    }
}

impl<T: ::buffa::Message> IntoResponse for BuffaConnectRpc<T> {
    fn into_response(self) -> Response {
        let BuffaConnectRpc(message) = self;

        (
            StatusCode::OK,
            [(header::CONTENT_TYPE, APPLICATION_PROTO)],
            message.encode_to_vec(),
        )
            .into_response()
    }
}

impl<T: ::buffa::Message> From<T> for BuffaConnectRpc<T> {
    fn from(value: T) -> Self {
        BuffaConnectRpc(value)
    }
}

/// Wrapper connect RPC type for a buffa message whose codec is negotiated per
/// request.
///
/// Unlike [`BuffaConnectRpc`], which is protobuf-only, this accepts both
/// `application/proto` and `application/json`, and answers in the codec the
/// caller used. Use it for services reachable from a web browser, which cannot
/// encode protobuf without pulling in a codec of its own.
///
/// A response can only be built with [`BuffaConnectRpcAny::reply`], which carries the
/// request's codec over, so a handler cannot answer in the wrong one:
///
/// ```ignore
/// async fn handler(
///     request: BuffaConnectRpcAny<MyRequest>,
/// ) -> Result<BuffaConnectRpcAny<MyResponse>, CrpcError> {
///     let response = do_work(&request.some_field)?;
///     Ok(request.reply(response))
/// }
/// ```
///
/// Errors need no codec: per the Connect protocol, a unary error response is
/// always a JSON [`CrpcError`] envelope, whichever codec the request used.
pub struct BuffaConnectRpcAny<T: CrpcOrJson> {
    message: T,
    codec: Codec,
}

impl<T: CrpcOrJson> BuffaConnectRpcAny<T> {
    /// Extract the inner message.
    pub fn into_inner(self) -> T {
        self.message
    }

    /// The codec this message was decoded from, or will be encoded with.
    pub fn codec(&self) -> Codec {
        self.codec
    }

    /// Wraps a response message with this request's codec.
    pub fn reply<U: CrpcOrJson>(&self, message: U) -> BuffaConnectRpcAny<U> {
        BuffaConnectRpcAny {
            message,
            codec: self.codec,
        }
    }

    /// Creates a new `BuffaConnectRpcAny` with the given message and codec.
    pub fn from_parts(message: T, codec: Codec) -> Self {
        BuffaConnectRpcAny { message, codec }
    }
}

impl<T: CrpcOrJson + Debug> std::fmt::Debug for BuffaConnectRpcAny<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("BuffaConnectRpcAny")
            .field("message", &self.message)
            .field("codec", &self.codec)
            .finish()
    }
}

impl<T: CrpcOrJson> std::ops::Deref for BuffaConnectRpcAny<T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        &self.message
    }
}

impl<S, T: CrpcOrJson> FromRequest<S> for BuffaConnectRpcAny<T>
where
    S: Send + Sync,
{
    type Rejection = ConnectRpcRejection;

    async fn from_request(req: Request, state: &S) -> Result<Self, Self::Rejection> {
        let codec = Codec::from_headers(req.headers())?;

        let bytes = Bytes::from_request(req, state)
            .await
            .map_err(ConnectRpcRejection::BytesRejection)?;

        let message = match codec {
            Codec::Proto => {
                T::decode_from_slice(&bytes).map_err(|_e| ConnectRpcRejection::DecodingFailed)?
            }
            Codec::Json => {
                serde_json::from_slice(&bytes).map_err(|_e| ConnectRpcRejection::DecodingFailed)?
            }
        };

        Ok(Self { message, codec })
    }
}

impl<T: CrpcOrJson> IntoResponse for BuffaConnectRpcAny<T> {
    fn into_response(self) -> Response {
        let body = match self.codec {
            Codec::Proto => self.message.encode_to_vec(),
            Codec::Json => {
                match serde_json::to_vec(&self.message) {
                    Ok(body) => body,
                    Err(_e) => {
                        return CrpcError::new(
                            CrpcErrorCode::Internal,
                            "failed to serialize response".to_string(),
                        )
                        .into_response();
                    }
                }
            }
        };

        (
            StatusCode::OK,
            [(header::CONTENT_TYPE, self.codec.content_type())],
            body,
        )
            .into_response()
    }
}

/// `BuffaConnectRpcAny` can only be used with types that are both buffa messages and
/// JSON serializable, so that it can decode and encode both codecs.
pub trait CrpcOrJson: ::buffa::Message + serde::de::DeserializeOwned + serde::Serialize {}
impl<AnyMessage: ::buffa::Message + serde::de::DeserializeOwned + serde::Serialize> CrpcOrJson
    for AnyMessage
{
}

#[cfg(test)]
mod tests {
    use axum::{
        extract::FromRequest as _,
        http::{StatusCode, header},
        response::IntoResponse as _,
    };

    use super::{BuffaConnectRpc, BuffaConnectRpcAny};
    use crate::extractor::{
        APPLICATION_JSON, APPLICATION_PROTO, Codec,
        tests::{body_of, extract, request},
    };

    /// A hand-written stand-in for a `buffa-codegen` message: `string name = 1`.
    ///
    /// buffa has no derive macro, so the `Message` impl mirrors what codegen
    /// emits for a single string field. Unknown fields are skipped rather than
    /// preserved, which the extractor does not care about.
    #[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
    struct Greeting {
        name: String,
    }

    buffa::impl_default_instance!(Greeting);

    impl buffa::Message for Greeting {
        fn compute_size(&self, _cache: &mut buffa::SizeCache) -> u32 {
            if self.name.is_empty() {
                0
            } else {
                1 + buffa::types::string_encoded_len(&self.name) as u32
            }
        }

        fn write_to(&self, _cache: &mut buffa::SizeCache, buf: &mut impl bytes::BufMut) {
            if !self.name.is_empty() {
                buffa::types::put_string_field(1, &self.name, buf);
            }
        }

        fn merge_field(
            &mut self,
            tag: buffa::encoding::Tag,
            buf: &mut impl bytes::Buf,
            ctx: buffa::DecodeContext<'_>,
        ) -> Result<(), buffa::DecodeError> {
            match tag.field_number() {
                1 => {
                    buffa::encoding::check_wire_type(
                        tag,
                        buffa::encoding::WireType::LengthDelimited,
                    )?;
                    buffa::types::merge_string(&mut self.name, buf)?;
                }
                _ => buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?,
            }
            Ok(())
        }

        fn clear(&mut self) {
            self.name.clear();
        }
    }

    #[test]
    fn into_response_sets_content_type_application_proto() {
        let response = BuffaConnectRpc(Greeting { name: "ada".into() }).into_response();

        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            response.headers().get(header::CONTENT_TYPE).unwrap(),
            APPLICATION_PROTO,
        );
    }

    #[test]
    fn proto_extractor_decodes_a_message() {
        let body = buffa::Message::encode_to_vec(&Greeting { name: "ada".into() });
        let extracted: BuffaConnectRpc<Greeting> = extract(BuffaConnectRpc::from_request(
            request(APPLICATION_PROTO, body),
            &(),
        ))
        .expect("proto body is accepted");

        assert_eq!(extracted.name, "ada");
    }

    #[test]
    fn proto_extractor_accepts_a_mixed_case_content_type() {
        let body = buffa::Message::encode_to_vec(&Greeting { name: "ada".into() });
        let extracted: BuffaConnectRpc<Greeting> = extract(BuffaConnectRpc::from_request(
            request("APPLICATION/PROTO", body),
            &(),
        ))
        .expect("mixed-case content type is accepted");

        assert_eq!(extracted.name, "ada");
    }

    #[test]
    fn proto_extractor_rejects_a_json_content_type() {
        let result: Result<BuffaConnectRpc<Greeting>, _> = extract(BuffaConnectRpc::from_request(
            request(APPLICATION_JSON, r#"{"name":"ada"}"#),
            &(),
        ));

        let response = result
            .expect_err("json is rejected by the proto-only extractor")
            .into_response();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        assert_eq!(body_of(response)["code"], "invalid_argument");
    }

    #[test]
    fn any_decodes_json_and_replies_in_json() {
        let extracted: BuffaConnectRpcAny<Greeting> = extract(BuffaConnectRpcAny::from_request(
            request(APPLICATION_JSON, r#"{"name":"ada"}"#),
            &(),
        ))
        .expect("json body is accepted");

        assert_eq!(extracted.codec(), Codec::Json);
        assert_eq!(extracted.name, "ada");

        let response = extracted
            .reply(Greeting { name: "ok".into() })
            .into_response();
        assert_eq!(
            response.headers().get(header::CONTENT_TYPE).unwrap(),
            APPLICATION_JSON,
        );
        let body = extract(axum::body::to_bytes(response.into_body(), usize::MAX))
            .expect("response body is readable");
        assert_eq!(body.as_ref(), br#"{"name":"ok"}"#);
    }

    #[test]
    fn any_decodes_proto_and_replies_in_proto() {
        let body = buffa::Message::encode_to_vec(&Greeting { name: "ada".into() });
        let extracted: BuffaConnectRpcAny<Greeting> = extract(BuffaConnectRpcAny::from_request(
            request(APPLICATION_PROTO, body),
            &(),
        ))
        .expect("proto body is accepted");

        assert_eq!(extracted.codec(), Codec::Proto);
        assert_eq!(extracted.name, "ada");

        let response = extracted
            .reply(Greeting { name: "ok".into() })
            .into_response();
        assert_eq!(
            response.headers().get(header::CONTENT_TYPE).unwrap(),
            APPLICATION_PROTO,
        );
        let body = extract(axum::body::to_bytes(response.into_body(), usize::MAX))
            .expect("response body is readable");
        let decoded: Greeting =
            buffa::Message::decode_from_slice(&body).expect("response body is a proto message");
        assert_eq!(decoded.name, "ok");
    }

    #[test]
    fn any_rejects_an_unsupported_content_type() {
        let result: Result<BuffaConnectRpcAny<Greeting>, _> = extract(
            BuffaConnectRpcAny::from_request(request("text/plain", "hi"), &()),
        );

        let response = result.expect_err("text/plain is rejected").into_response();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        assert_eq!(body_of(response)["code"], "invalid_argument");
    }

    #[test]
    fn any_rejects_a_malformed_json_body() {
        let result: Result<BuffaConnectRpcAny<Greeting>, _> = extract(
            BuffaConnectRpcAny::from_request(request(APPLICATION_JSON, "{not json"), &()),
        );

        let response = result
            .expect_err("malformed json is rejected")
            .into_response();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
    }
}
