// @generated by buffa-codegen. DO NOT EDIT.
// source: endhost/v1/segments_service.proto

/// List segments request.
#[derive(Clone, Debug, Default)]
pub struct ListSegmentsRequestView<'a> {
    /// The source ISD-AS of the final end-to-end path. This is most likely
    /// the requester's own ISD-AS.
    ///
    /// Field 1: `src_isd_as`
    pub src_isd_as: u64,
    /// The destination ISD-AS the final end-to-end path.
    ///
    /// Field 2: `dst_isd_as`
    pub dst_isd_as: u64,
    /// The maximum total number of segments to return.
    /// The service may return fewer than this value.
    /// If unspecified, the maximum number of segments
    /// per page is returned, which is 64.
    ///
    /// Field 3: `page_size`
    pub page_size: i32,
    /// A page token, received from a previous
    /// ListSegmentsRequest call.
    /// Provide this to retrieve the subsequent page.
    ///
    /// When paginating, all other parameters provided in
    /// ListSegmentsRequest must match the call that provided
    /// the page token.
    ///
    /// Field 4: `page_token`
    pub page_token: &'a str,
}
impl<'a> ::buffa::MessageView<'a> for ListSegmentsRequestView<'a> {
    type Owned = super::super::ListSegmentsRequest;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.src_isd_as = ::buffa::types::decode_uint64(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.dst_isd_as = ::buffa::types::decode_uint64(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.page_size = ::buffa::types::decode_int32(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.page_token = ::buffa::types::borrow_str(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::ListSegmentsRequest,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::ListSegmentsRequest,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::ListSegmentsRequest {
            src_isd_as: self.src_isd_as,
            dst_isd_as: self.dst_isd_as,
            page_size: self.page_size,
            page_token: self.page_token.to_string(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for ListSegmentsRequestView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.src_isd_as != 0u64 {
            size += 1u32 + ::buffa::types::uint64_encoded_len(self.src_isd_as) as u32;
        }
        if self.dst_isd_as != 0u64 {
            size += 1u32 + ::buffa::types::uint64_encoded_len(self.dst_isd_as) as u32;
        }
        if self.page_size != 0i32 {
            size += 1u32 + ::buffa::types::int32_encoded_len(self.page_size) as u32;
        }
        if !self.page_token.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.page_token) as u32;
        }
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.src_isd_as != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.src_isd_as, buf);
        }
        if self.dst_isd_as != 0u64 {
            ::buffa::types::put_uint64_field(2u32, self.dst_isd_as, buf);
        }
        if self.page_size != 0i32 {
            ::buffa::types::put_int32_field(3u32, self.page_size, buf);
        }
        if !self.page_token.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.page_token, buf);
        }
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for ListSegmentsRequestView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !::buffa::json_helpers::skip_if::is_zero_u64(&self.src_isd_as) {
            __map
                .serialize_entry(
                    "srcIsdAs",
                    &::buffa::json_helpers::ProtoJson(&self.src_isd_as),
                )?;
        }
        if !::buffa::json_helpers::skip_if::is_zero_u64(&self.dst_isd_as) {
            __map
                .serialize_entry(
                    "dstIsdAs",
                    &::buffa::json_helpers::ProtoJson(&self.dst_isd_as),
                )?;
        }
        if !::buffa::json_helpers::skip_if::is_zero_i32(&self.page_size) {
            __map
                .serialize_entry(
                    "pageSize",
                    &::buffa::json_helpers::ProtoJson(&self.page_size),
                )?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_str(self.page_token) {
            __map.serialize_entry("pageToken", self.page_token)?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for ListSegmentsRequestView<'a> {
    const PACKAGE: &'static str = "scion.endhost.v1";
    const NAME: &'static str = "ListSegmentsRequest";
    const FULL_NAME: &'static str = "scion.endhost.v1.ListSegmentsRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/scion.endhost.v1.ListSegmentsRequest";
}
::buffa::impl_default_view_instance!(ListSegmentsRequestView);
::buffa::impl_view_reborrow!(ListSegmentsRequestView);
/** Self-contained, `'static` owned view of a `ListSegmentsRequest` message.

 Wraps [`::buffa::OwnedView`]`<`[`ListSegmentsRequestView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`ListSegmentsRequestView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct ListSegmentsRequestOwnedView(
    ::buffa::OwnedView<ListSegmentsRequestView<'static>>,
);
impl ListSegmentsRequestOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ListSegmentsRequestOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ListSegmentsRequestOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::ListSegmentsRequest,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ListSegmentsRequestOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`ListSegmentsRequestView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &ListSegmentsRequestView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::ListSegmentsRequest,
        ::buffa::DecodeError,
    > {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// The source ISD-AS of the final end-to-end path. This is most likely
    /// the requester's own ISD-AS.
    ///
    /// Field 1: `src_isd_as`
    #[must_use]
    pub fn src_isd_as(&self) -> u64 {
        self.0.reborrow().src_isd_as
    }
    /// The destination ISD-AS the final end-to-end path.
    ///
    /// Field 2: `dst_isd_as`
    #[must_use]
    pub fn dst_isd_as(&self) -> u64 {
        self.0.reborrow().dst_isd_as
    }
    /// The maximum total number of segments to return.
    /// The service may return fewer than this value.
    /// If unspecified, the maximum number of segments
    /// per page is returned, which is 64.
    ///
    /// Field 3: `page_size`
    #[must_use]
    pub fn page_size(&self) -> i32 {
        self.0.reborrow().page_size
    }
    /// A page token, received from a previous
    /// ListSegmentsRequest call.
    /// Provide this to retrieve the subsequent page.
    ///
    /// When paginating, all other parameters provided in
    /// ListSegmentsRequest must match the call that provided
    /// the page token.
    ///
    /// Field 4: `page_token`
    #[must_use]
    pub fn page_token(&self) -> &'_ str {
        self.0.reborrow().page_token
    }
}
impl ::core::convert::From<::buffa::OwnedView<ListSegmentsRequestView<'static>>>
for ListSegmentsRequestOwnedView {
    fn from(inner: ::buffa::OwnedView<ListSegmentsRequestView<'static>>) -> Self {
        ListSegmentsRequestOwnedView(inner)
    }
}
impl ::core::convert::From<ListSegmentsRequestOwnedView>
for ::buffa::OwnedView<ListSegmentsRequestView<'static>> {
    fn from(wrapper: ListSegmentsRequestOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<ListSegmentsRequestView<'static>>>
for ListSegmentsRequestOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<ListSegmentsRequestView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::ListSegmentsRequest {
    type View<'a> = ListSegmentsRequestView<'a>;
    type ViewHandle = ListSegmentsRequestOwnedView;
}
impl ::serde::Serialize for ListSegmentsRequestOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
/// ListSegmentsReponse includes up, down, and core path segments that
/// can be combined to end-to-end paths.
#[derive(Clone, Debug, Default)]
pub struct ListSegmentsResponseView<'a> {
    /// The list of returned up path segments.
    ///
    /// Field 1: `up_segments`
    pub up_segments: ::buffa::RepeatedView<
        'a,
        ::scion_protobuf::proto::control_plane::v1::__buffa::view::PathSegmentView<'a>,
    >,
    /// The list of returned down path segments.
    ///
    /// Field 2: `down_segments`
    pub down_segments: ::buffa::RepeatedView<
        'a,
        ::scion_protobuf::proto::control_plane::v1::__buffa::view::PathSegmentView<'a>,
    >,
    /// The list of returned core path segments.
    ///
    /// Field 3: `core_segments`
    pub core_segments: ::buffa::RepeatedView<
        'a,
        ::scion_protobuf::proto::control_plane::v1::__buffa::view::PathSegmentView<'a>,
    >,
    /// The token for the next page of results.
    ///
    /// Field 4: `next_page_token`
    pub next_page_token: &'a str,
}
impl<'a> ::buffa::MessageView<'a> for ListSegmentsResponseView<'a> {
    type Owned = super::super::ListSegmentsResponse;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.next_page_token = ::buffa::types::borrow_str(&mut cur)?;
            }
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                view.up_segments
                    .push(
                        <::scion_protobuf::proto::control_plane::v1::__buffa::view::PathSegmentView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                view.down_segments
                    .push(
                        <::scion_protobuf::proto::control_plane::v1::__buffa::view::PathSegmentView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                view.core_segments
                    .push(
                        <::scion_protobuf::proto::control_plane::v1::__buffa::view::PathSegmentView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::ListSegmentsResponse,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::ListSegmentsResponse,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::ListSegmentsResponse {
            up_segments: self
                .up_segments
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            down_segments: self
                .down_segments
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            core_segments: self
                .core_segments
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            next_page_token: self.next_page_token.to_string(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for ListSegmentsResponseView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        for v in &self.up_segments {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        for v in &self.down_segments {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        for v in &self.core_segments {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        if !self.next_page_token.is_empty() {
            size
                += 1u32
                    + ::buffa::types::string_encoded_len(&self.next_page_token) as u32;
        }
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.up_segments {
            ::buffa::types::put_len_delimited_header(1u32, __cache.consume_next(), buf);
            v.write_to(__cache, buf);
        }
        for v in &self.down_segments {
            ::buffa::types::put_len_delimited_header(2u32, __cache.consume_next(), buf);
            v.write_to(__cache, buf);
        }
        for v in &self.core_segments {
            ::buffa::types::put_len_delimited_header(3u32, __cache.consume_next(), buf);
            v.write_to(__cache, buf);
        }
        if !self.next_page_token.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.next_page_token, buf);
        }
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for ListSegmentsResponseView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !self.up_segments.is_empty() {
            __map.serialize_entry("upSegments", &*self.up_segments)?;
        }
        if !self.down_segments.is_empty() {
            __map.serialize_entry("downSegments", &*self.down_segments)?;
        }
        if !self.core_segments.is_empty() {
            __map.serialize_entry("coreSegments", &*self.core_segments)?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_str(self.next_page_token) {
            __map.serialize_entry("nextPageToken", self.next_page_token)?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for ListSegmentsResponseView<'a> {
    const PACKAGE: &'static str = "scion.endhost.v1";
    const NAME: &'static str = "ListSegmentsResponse";
    const FULL_NAME: &'static str = "scion.endhost.v1.ListSegmentsResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/scion.endhost.v1.ListSegmentsResponse";
}
::buffa::impl_default_view_instance!(ListSegmentsResponseView);
::buffa::impl_view_reborrow!(ListSegmentsResponseView);
/** Self-contained, `'static` owned view of a `ListSegmentsResponse` message.

 Wraps [`::buffa::OwnedView`]`<`[`ListSegmentsResponseView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`ListSegmentsResponseView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct ListSegmentsResponseOwnedView(
    ::buffa::OwnedView<ListSegmentsResponseView<'static>>,
);
impl ListSegmentsResponseOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ListSegmentsResponseOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ListSegmentsResponseOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::ListSegmentsResponse,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ListSegmentsResponseOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`ListSegmentsResponseView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &ListSegmentsResponseView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::ListSegmentsResponse,
        ::buffa::DecodeError,
    > {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// The list of returned up path segments.
    ///
    /// Field 1: `up_segments`
    #[must_use]
    pub fn up_segments(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        ::scion_protobuf::proto::control_plane::v1::__buffa::view::PathSegmentView<'_>,
    > {
        &self.0.reborrow().up_segments
    }
    /// The list of returned down path segments.
    ///
    /// Field 2: `down_segments`
    #[must_use]
    pub fn down_segments(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        ::scion_protobuf::proto::control_plane::v1::__buffa::view::PathSegmentView<'_>,
    > {
        &self.0.reborrow().down_segments
    }
    /// The list of returned core path segments.
    ///
    /// Field 3: `core_segments`
    #[must_use]
    pub fn core_segments(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        ::scion_protobuf::proto::control_plane::v1::__buffa::view::PathSegmentView<'_>,
    > {
        &self.0.reborrow().core_segments
    }
    /// The token for the next page of results.
    ///
    /// Field 4: `next_page_token`
    #[must_use]
    pub fn next_page_token(&self) -> &'_ str {
        self.0.reborrow().next_page_token
    }
}
impl ::core::convert::From<::buffa::OwnedView<ListSegmentsResponseView<'static>>>
for ListSegmentsResponseOwnedView {
    fn from(inner: ::buffa::OwnedView<ListSegmentsResponseView<'static>>) -> Self {
        ListSegmentsResponseOwnedView(inner)
    }
}
impl ::core::convert::From<ListSegmentsResponseOwnedView>
for ::buffa::OwnedView<ListSegmentsResponseView<'static>> {
    fn from(wrapper: ListSegmentsResponseOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<ListSegmentsResponseView<'static>>>
for ListSegmentsResponseOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<ListSegmentsResponseView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::ListSegmentsResponse {
    type View<'a> = ListSegmentsResponseView<'a>;
    type ViewHandle = ListSegmentsResponseOwnedView;
}
impl ::serde::Serialize for ListSegmentsResponseOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
