// @generated by buffa-codegen. DO NOT EDIT.
// source: proto/control_plane/v1/cppki.proto

#[derive(Clone, Debug, Default)]
pub struct ChainsRequestView<'a> {
    /// Field 1: `isd_as`
    pub isd_as: u64,
    /// Field 2: `subject_key_id`
    pub subject_key_id: &'a [u8],
    /// Field 3: `at_least_valid_until`
    pub at_least_valid_until: ::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'a>,
    >,
    /// Field 4: `at_least_valid_since`
    pub at_least_valid_since: ::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'a>,
    >,
    pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
}
impl<'a> ::buffa::MessageView<'a> for ChainsRequestView<'a> {
    type Owned = super::super::ChainsRequest;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.isd_as = ::buffa::types::decode_uint64(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.subject_key_id = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                match view.at_least_valid_until.as_mut() {
                    Some(existing) => {
                        ::buffa::MessageView::merge_into_view(existing, sub, __sub_ctx)?
                    }
                    None => {
                        view.at_least_valid_until = ::buffa::MessageFieldView::set(
                            <::buffa_types::google::protobuf::__buffa::view::TimestampView as ::buffa::MessageView>::decode_view_ctx(
                                sub,
                                __sub_ctx,
                            )?,
                        );
                    }
                }
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                match view.at_least_valid_since.as_mut() {
                    Some(existing) => {
                        ::buffa::MessageView::merge_into_view(existing, sub, __sub_ctx)?
                    }
                    None => {
                        view.at_least_valid_since = ::buffa::MessageFieldView::set(
                            <::buffa_types::google::protobuf::__buffa::view::TimestampView as ::buffa::MessageView>::decode_view_ctx(
                                sub,
                                __sub_ctx,
                            )?,
                        );
                    }
                }
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                let span_len = before_tag.len() - cur.len();
                view.__buffa_unknown_fields.push_record(before_tag, span_len, ctx)?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::ChainsRequest, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::ChainsRequest, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::ChainsRequest {
            isd_as: self.isd_as,
            subject_key_id: (self.subject_key_id).to_vec(),
            at_least_valid_until: match self.at_least_valid_until.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        ::buffa_types::google::protobuf::Timestamp,
                    >::some(v.to_owned_from_source(__buffa_src)?)
                }
                None => ::buffa::MessageField::none(),
            },
            at_least_valid_since: match self.at_least_valid_since.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        ::buffa_types::google::protobuf::Timestamp,
                    >::some(v.to_owned_from_source(__buffa_src)?)
                }
                None => ::buffa::MessageField::none(),
            },
            __buffa_unknown_fields: self.__buffa_unknown_fields.to_owned()?.into(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for ChainsRequestView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.isd_as != 0u64 {
            size += 1u32 + ::buffa::types::uint64_encoded_len(self.isd_as) as u32;
        }
        if !self.subject_key_id.is_empty() {
            size
                += 1u32 + ::buffa::types::bytes_encoded_len(&self.subject_key_id) as u32;
        }
        if self.at_least_valid_until.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.at_least_valid_until.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        if self.at_least_valid_since.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.at_least_valid_since.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.isd_as != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.isd_as, buf);
        }
        if !self.subject_key_id.is_empty() {
            ::buffa::types::put_bytes_field(2u32, &self.subject_key_id, buf);
        }
        if self.at_least_valid_until.is_set() {
            ::buffa::types::put_len_delimited_header(3u32, __cache.consume_next(), buf);
            self.at_least_valid_until.write_to(__cache, buf);
        }
        if self.at_least_valid_since.is_set() {
            ::buffa::types::put_len_delimited_header(4u32, __cache.consume_next(), buf);
            self.at_least_valid_since.write_to(__cache, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for ChainsRequestView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !::buffa::json_helpers::skip_if::is_zero_u64(&self.isd_as) {
            __map
                .serialize_entry(
                    "isdAs",
                    &::buffa::json_helpers::ProtoJson(&self.isd_as),
                )?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_bytes(self.subject_key_id) {
            __map
                .serialize_entry(
                    "subjectKeyId",
                    &::buffa::json_helpers::BytesJson(self.subject_key_id),
                )?;
        }
        {
            if let ::core::option::Option::Some(__v) = self
                .at_least_valid_until
                .as_option()
            {
                __map.serialize_entry("atLeastValidUntil", __v)?;
            }
        }
        {
            if let ::core::option::Option::Some(__v) = self
                .at_least_valid_since
                .as_option()
            {
                __map.serialize_entry("atLeastValidSince", __v)?;
            }
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for ChainsRequestView<'a> {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "ChainsRequest";
    const FULL_NAME: &'static str = "proto.control_plane.v1.ChainsRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.ChainsRequest";
}
::buffa::impl_default_view_instance!(ChainsRequestView);
::buffa::impl_view_reborrow!(ChainsRequestView);
/** Self-contained, `'static` owned view of a `ChainsRequest` message.

 Wraps [`::buffa::OwnedView`]`<`[`ChainsRequestView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`ChainsRequestView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct ChainsRequestOwnedView(::buffa::OwnedView<ChainsRequestView<'static>>);
impl ChainsRequestOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ChainsRequestOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ChainsRequestOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::ChainsRequest,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ChainsRequestOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`ChainsRequestView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &ChainsRequestView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::ChainsRequest, ::buffa::DecodeError> {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `isd_as`
    #[must_use]
    pub fn isd_as(&self) -> u64 {
        self.0.reborrow().isd_as
    }
    /// Field 2: `subject_key_id`
    #[must_use]
    pub fn subject_key_id(&self) -> &'_ [u8] {
        self.0.reborrow().subject_key_id
    }
    /// Field 3: `at_least_valid_until`
    #[must_use]
    pub fn at_least_valid_until(
        &self,
    ) -> &::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'_>,
    > {
        &self.0.reborrow().at_least_valid_until
    }
    /// Field 4: `at_least_valid_since`
    #[must_use]
    pub fn at_least_valid_since(
        &self,
    ) -> &::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'_>,
    > {
        &self.0.reborrow().at_least_valid_since
    }
}
impl ::core::convert::From<::buffa::OwnedView<ChainsRequestView<'static>>>
for ChainsRequestOwnedView {
    fn from(inner: ::buffa::OwnedView<ChainsRequestView<'static>>) -> Self {
        ChainsRequestOwnedView(inner)
    }
}
impl ::core::convert::From<ChainsRequestOwnedView>
for ::buffa::OwnedView<ChainsRequestView<'static>> {
    fn from(wrapper: ChainsRequestOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<ChainsRequestView<'static>>>
for ChainsRequestOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<ChainsRequestView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::ChainsRequest {
    type View<'a> = ChainsRequestView<'a>;
    type ViewHandle = ChainsRequestOwnedView;
}
impl ::serde::Serialize for ChainsRequestOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
#[derive(Clone, Debug, Default)]
pub struct ChainsResponseView<'a> {
    /// Field 1: `chains`
    pub chains: ::buffa::RepeatedView<'a, super::super::__buffa::view::ChainView<'a>>,
    pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
}
impl<'a> ::buffa::MessageView<'a> for ChainsResponseView<'a> {
    type Owned = super::super::ChainsResponse;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                view.chains
                    .push(
                        <super::super::__buffa::view::ChainView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                let span_len = before_tag.len() - cur.len();
                view.__buffa_unknown_fields.push_record(before_tag, span_len, ctx)?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::ChainsResponse, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::ChainsResponse, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::ChainsResponse {
            chains: self
                .chains
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            __buffa_unknown_fields: self.__buffa_unknown_fields.to_owned()?.into(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for ChainsResponseView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        for v in &self.chains {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.chains {
            ::buffa::types::put_len_delimited_header(1u32, __cache.consume_next(), buf);
            v.write_to(__cache, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for ChainsResponseView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !self.chains.is_empty() {
            __map.serialize_entry("chains", &*self.chains)?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for ChainsResponseView<'a> {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "ChainsResponse";
    const FULL_NAME: &'static str = "proto.control_plane.v1.ChainsResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.ChainsResponse";
}
::buffa::impl_default_view_instance!(ChainsResponseView);
::buffa::impl_view_reborrow!(ChainsResponseView);
/** Self-contained, `'static` owned view of a `ChainsResponse` message.

 Wraps [`::buffa::OwnedView`]`<`[`ChainsResponseView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`ChainsResponseView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct ChainsResponseOwnedView(::buffa::OwnedView<ChainsResponseView<'static>>);
impl ChainsResponseOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ChainsResponseOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ChainsResponseOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::ChainsResponse,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ChainsResponseOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`ChainsResponseView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &ChainsResponseView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::ChainsResponse, ::buffa::DecodeError> {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `chains`
    #[must_use]
    pub fn chains(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::ChainView<'_>> {
        &self.0.reborrow().chains
    }
}
impl ::core::convert::From<::buffa::OwnedView<ChainsResponseView<'static>>>
for ChainsResponseOwnedView {
    fn from(inner: ::buffa::OwnedView<ChainsResponseView<'static>>) -> Self {
        ChainsResponseOwnedView(inner)
    }
}
impl ::core::convert::From<ChainsResponseOwnedView>
for ::buffa::OwnedView<ChainsResponseView<'static>> {
    fn from(wrapper: ChainsResponseOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<ChainsResponseView<'static>>>
for ChainsResponseOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<ChainsResponseView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::ChainsResponse {
    type View<'a> = ChainsResponseView<'a>;
    type ViewHandle = ChainsResponseOwnedView;
}
impl ::serde::Serialize for ChainsResponseOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
#[derive(Clone, Debug, Default)]
pub struct ChainView<'a> {
    /// Field 1: `as_cert`
    pub as_cert: &'a [u8],
    /// Field 2: `ca_cert`
    pub ca_cert: &'a [u8],
    pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
}
impl<'a> ::buffa::MessageView<'a> for ChainView<'a> {
    type Owned = super::super::Chain;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.as_cert = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.ca_cert = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                let span_len = before_tag.len() - cur.len();
                view.__buffa_unknown_fields.push_record(before_tag, span_len, ctx)?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Chain, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Chain, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Chain {
            as_cert: (self.as_cert).to_vec(),
            ca_cert: (self.ca_cert).to_vec(),
            __buffa_unknown_fields: self.__buffa_unknown_fields.to_owned()?.into(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for ChainView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.as_cert.is_empty() {
            size += 1u32 + ::buffa::types::bytes_encoded_len(&self.as_cert) as u32;
        }
        if !self.ca_cert.is_empty() {
            size += 1u32 + ::buffa::types::bytes_encoded_len(&self.ca_cert) as u32;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.as_cert.is_empty() {
            ::buffa::types::put_bytes_field(1u32, &self.as_cert, buf);
        }
        if !self.ca_cert.is_empty() {
            ::buffa::types::put_bytes_field(2u32, &self.ca_cert, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for ChainView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !::buffa::json_helpers::skip_if::is_empty_bytes(self.as_cert) {
            __map
                .serialize_entry(
                    "asCert",
                    &::buffa::json_helpers::BytesJson(self.as_cert),
                )?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_bytes(self.ca_cert) {
            __map
                .serialize_entry(
                    "caCert",
                    &::buffa::json_helpers::BytesJson(self.ca_cert),
                )?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for ChainView<'a> {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "Chain";
    const FULL_NAME: &'static str = "proto.control_plane.v1.Chain";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.Chain";
}
::buffa::impl_default_view_instance!(ChainView);
::buffa::impl_view_reborrow!(ChainView);
/** Self-contained, `'static` owned view of a `Chain` message.

 Wraps [`::buffa::OwnedView`]`<`[`ChainView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`ChainView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct ChainOwnedView(::buffa::OwnedView<ChainView<'static>>);
impl ChainOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(ChainOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ChainOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Chain,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(ChainOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`ChainView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &ChainView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Chain, ::buffa::DecodeError> {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `as_cert`
    #[must_use]
    pub fn as_cert(&self) -> &'_ [u8] {
        self.0.reborrow().as_cert
    }
    /// Field 2: `ca_cert`
    #[must_use]
    pub fn ca_cert(&self) -> &'_ [u8] {
        self.0.reborrow().ca_cert
    }
}
impl ::core::convert::From<::buffa::OwnedView<ChainView<'static>>> for ChainOwnedView {
    fn from(inner: ::buffa::OwnedView<ChainView<'static>>) -> Self {
        ChainOwnedView(inner)
    }
}
impl ::core::convert::From<ChainOwnedView> for ::buffa::OwnedView<ChainView<'static>> {
    fn from(wrapper: ChainOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<ChainView<'static>>> for ChainOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<ChainView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Chain {
    type View<'a> = ChainView<'a>;
    type ViewHandle = ChainOwnedView;
}
impl ::serde::Serialize for ChainOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
#[derive(Clone, Debug, Default)]
pub struct TRCRequestView<'a> {
    /// Field 1: `isd`
    pub isd: u32,
    /// Field 2: `base`
    pub base: u64,
    /// Field 3: `serial`
    pub serial: u64,
    pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
}
impl<'a> ::buffa::MessageView<'a> for TRCRequestView<'a> {
    type Owned = super::super::TRCRequest;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.isd = ::buffa::types::decode_uint32(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.base = ::buffa::types::decode_uint64(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.serial = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                let span_len = before_tag.len() - cur.len();
                view.__buffa_unknown_fields.push_record(before_tag, span_len, ctx)?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::TRCRequest, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::TRCRequest, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::TRCRequest {
            isd: self.isd,
            base: self.base,
            serial: self.serial,
            __buffa_unknown_fields: self.__buffa_unknown_fields.to_owned()?.into(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for TRCRequestView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.isd != 0u32 {
            size += 1u32 + ::buffa::types::uint32_encoded_len(self.isd) as u32;
        }
        if self.base != 0u64 {
            size += 1u32 + ::buffa::types::uint64_encoded_len(self.base) as u32;
        }
        if self.serial != 0u64 {
            size += 1u32 + ::buffa::types::uint64_encoded_len(self.serial) as u32;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.isd != 0u32 {
            ::buffa::types::put_uint32_field(1u32, self.isd, buf);
        }
        if self.base != 0u64 {
            ::buffa::types::put_uint64_field(2u32, self.base, buf);
        }
        if self.serial != 0u64 {
            ::buffa::types::put_uint64_field(3u32, self.serial, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for TRCRequestView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !::buffa::json_helpers::skip_if::is_zero_u32(&self.isd) {
            __map.serialize_entry("isd", &::buffa::json_helpers::ProtoJson(&self.isd))?;
        }
        if !::buffa::json_helpers::skip_if::is_zero_u64(&self.base) {
            __map
                .serialize_entry("base", &::buffa::json_helpers::ProtoJson(&self.base))?;
        }
        if !::buffa::json_helpers::skip_if::is_zero_u64(&self.serial) {
            __map
                .serialize_entry(
                    "serial",
                    &::buffa::json_helpers::ProtoJson(&self.serial),
                )?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for TRCRequestView<'a> {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "TRCRequest";
    const FULL_NAME: &'static str = "proto.control_plane.v1.TRCRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.TRCRequest";
}
::buffa::impl_default_view_instance!(TRCRequestView);
::buffa::impl_view_reborrow!(TRCRequestView);
/** Self-contained, `'static` owned view of a `TRCRequest` message.

 Wraps [`::buffa::OwnedView`]`<`[`TRCRequestView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`TRCRequestView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct TRCRequestOwnedView(::buffa::OwnedView<TRCRequestView<'static>>);
impl TRCRequestOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            TRCRequestOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            TRCRequestOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::TRCRequest,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            TRCRequestOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`TRCRequestView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &TRCRequestView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::TRCRequest, ::buffa::DecodeError> {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `isd`
    #[must_use]
    pub fn isd(&self) -> u32 {
        self.0.reborrow().isd
    }
    /// Field 2: `base`
    #[must_use]
    pub fn base(&self) -> u64 {
        self.0.reborrow().base
    }
    /// Field 3: `serial`
    #[must_use]
    pub fn serial(&self) -> u64 {
        self.0.reborrow().serial
    }
}
impl ::core::convert::From<::buffa::OwnedView<TRCRequestView<'static>>>
for TRCRequestOwnedView {
    fn from(inner: ::buffa::OwnedView<TRCRequestView<'static>>) -> Self {
        TRCRequestOwnedView(inner)
    }
}
impl ::core::convert::From<TRCRequestOwnedView>
for ::buffa::OwnedView<TRCRequestView<'static>> {
    fn from(wrapper: TRCRequestOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<TRCRequestView<'static>>>
for TRCRequestOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<TRCRequestView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::TRCRequest {
    type View<'a> = TRCRequestView<'a>;
    type ViewHandle = TRCRequestOwnedView;
}
impl ::serde::Serialize for TRCRequestOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
#[derive(Clone, Debug, Default)]
pub struct TRCResponseView<'a> {
    /// Field 1: `trc`
    pub trc: &'a [u8],
    pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
}
impl<'a> ::buffa::MessageView<'a> for TRCResponseView<'a> {
    type Owned = super::super::TRCResponse;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.trc = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                let span_len = before_tag.len() - cur.len();
                view.__buffa_unknown_fields.push_record(before_tag, span_len, ctx)?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::TRCResponse, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::TRCResponse, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::TRCResponse {
            trc: (self.trc).to_vec(),
            __buffa_unknown_fields: self.__buffa_unknown_fields.to_owned()?.into(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for TRCResponseView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.trc.is_empty() {
            size += 1u32 + ::buffa::types::bytes_encoded_len(&self.trc) as u32;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.trc.is_empty() {
            ::buffa::types::put_bytes_field(1u32, &self.trc, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for TRCResponseView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !::buffa::json_helpers::skip_if::is_empty_bytes(self.trc) {
            __map.serialize_entry("trc", &::buffa::json_helpers::BytesJson(self.trc))?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for TRCResponseView<'a> {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "TRCResponse";
    const FULL_NAME: &'static str = "proto.control_plane.v1.TRCResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.TRCResponse";
}
::buffa::impl_default_view_instance!(TRCResponseView);
::buffa::impl_view_reborrow!(TRCResponseView);
/** Self-contained, `'static` owned view of a `TRCResponse` message.

 Wraps [`::buffa::OwnedView`]`<`[`TRCResponseView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`TRCResponseView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct TRCResponseOwnedView(::buffa::OwnedView<TRCResponseView<'static>>);
impl TRCResponseOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            TRCResponseOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            TRCResponseOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::TRCResponse,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            TRCResponseOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`TRCResponseView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &TRCResponseView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::TRCResponse, ::buffa::DecodeError> {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `trc`
    #[must_use]
    pub fn trc(&self) -> &'_ [u8] {
        self.0.reborrow().trc
    }
}
impl ::core::convert::From<::buffa::OwnedView<TRCResponseView<'static>>>
for TRCResponseOwnedView {
    fn from(inner: ::buffa::OwnedView<TRCResponseView<'static>>) -> Self {
        TRCResponseOwnedView(inner)
    }
}
impl ::core::convert::From<TRCResponseOwnedView>
for ::buffa::OwnedView<TRCResponseView<'static>> {
    fn from(wrapper: TRCResponseOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<TRCResponseView<'static>>>
for TRCResponseOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<TRCResponseView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::TRCResponse {
    type View<'a> = TRCResponseView<'a>;
    type ViewHandle = TRCResponseOwnedView;
}
impl ::serde::Serialize for TRCResponseOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
#[derive(Clone, Debug, Default)]
pub struct VerificationKeyIDView<'a> {
    /// Field 1: `isd_as`
    pub isd_as: u64,
    /// Field 2: `subject_key_id`
    pub subject_key_id: &'a [u8],
    /// Field 3: `trc_base`
    pub trc_base: u64,
    /// Field 4: `trc_serial`
    pub trc_serial: u64,
    pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
}
impl<'a> ::buffa::MessageView<'a> for VerificationKeyIDView<'a> {
    type Owned = super::super::VerificationKeyID;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.isd_as = ::buffa::types::decode_uint64(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.subject_key_id = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.trc_base = ::buffa::types::decode_uint64(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.trc_serial = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                let span_len = before_tag.len() - cur.len();
                view.__buffa_unknown_fields.push_record(before_tag, span_len, ctx)?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::VerificationKeyID, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::VerificationKeyID, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::VerificationKeyID {
            isd_as: self.isd_as,
            subject_key_id: (self.subject_key_id).to_vec(),
            trc_base: self.trc_base,
            trc_serial: self.trc_serial,
            __buffa_unknown_fields: self.__buffa_unknown_fields.to_owned()?.into(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for VerificationKeyIDView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.isd_as != 0u64 {
            size += 1u32 + ::buffa::types::uint64_encoded_len(self.isd_as) as u32;
        }
        if !self.subject_key_id.is_empty() {
            size
                += 1u32 + ::buffa::types::bytes_encoded_len(&self.subject_key_id) as u32;
        }
        if self.trc_base != 0u64 {
            size += 1u32 + ::buffa::types::uint64_encoded_len(self.trc_base) as u32;
        }
        if self.trc_serial != 0u64 {
            size += 1u32 + ::buffa::types::uint64_encoded_len(self.trc_serial) as u32;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.isd_as != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.isd_as, buf);
        }
        if !self.subject_key_id.is_empty() {
            ::buffa::types::put_bytes_field(2u32, &self.subject_key_id, buf);
        }
        if self.trc_base != 0u64 {
            ::buffa::types::put_uint64_field(3u32, self.trc_base, buf);
        }
        if self.trc_serial != 0u64 {
            ::buffa::types::put_uint64_field(4u32, self.trc_serial, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for VerificationKeyIDView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !::buffa::json_helpers::skip_if::is_zero_u64(&self.isd_as) {
            __map
                .serialize_entry(
                    "isdAs",
                    &::buffa::json_helpers::ProtoJson(&self.isd_as),
                )?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_bytes(self.subject_key_id) {
            __map
                .serialize_entry(
                    "subjectKeyId",
                    &::buffa::json_helpers::BytesJson(self.subject_key_id),
                )?;
        }
        if !::buffa::json_helpers::skip_if::is_zero_u64(&self.trc_base) {
            __map
                .serialize_entry(
                    "trcBase",
                    &::buffa::json_helpers::ProtoJson(&self.trc_base),
                )?;
        }
        if !::buffa::json_helpers::skip_if::is_zero_u64(&self.trc_serial) {
            __map
                .serialize_entry(
                    "trcSerial",
                    &::buffa::json_helpers::ProtoJson(&self.trc_serial),
                )?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for VerificationKeyIDView<'a> {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "VerificationKeyID";
    const FULL_NAME: &'static str = "proto.control_plane.v1.VerificationKeyID";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.VerificationKeyID";
}
::buffa::impl_default_view_instance!(VerificationKeyIDView);
::buffa::impl_view_reborrow!(VerificationKeyIDView);
/** Self-contained, `'static` owned view of a `VerificationKeyID` message.

 Wraps [`::buffa::OwnedView`]`<`[`VerificationKeyIDView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`VerificationKeyIDView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct VerificationKeyIDOwnedView(
    ::buffa::OwnedView<VerificationKeyIDView<'static>>,
);
impl VerificationKeyIDOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            VerificationKeyIDOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            VerificationKeyIDOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::VerificationKeyID,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            VerificationKeyIDOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`VerificationKeyIDView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &VerificationKeyIDView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::VerificationKeyID, ::buffa::DecodeError> {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `isd_as`
    #[must_use]
    pub fn isd_as(&self) -> u64 {
        self.0.reborrow().isd_as
    }
    /// Field 2: `subject_key_id`
    #[must_use]
    pub fn subject_key_id(&self) -> &'_ [u8] {
        self.0.reborrow().subject_key_id
    }
    /// Field 3: `trc_base`
    #[must_use]
    pub fn trc_base(&self) -> u64 {
        self.0.reborrow().trc_base
    }
    /// Field 4: `trc_serial`
    #[must_use]
    pub fn trc_serial(&self) -> u64 {
        self.0.reborrow().trc_serial
    }
}
impl ::core::convert::From<::buffa::OwnedView<VerificationKeyIDView<'static>>>
for VerificationKeyIDOwnedView {
    fn from(inner: ::buffa::OwnedView<VerificationKeyIDView<'static>>) -> Self {
        VerificationKeyIDOwnedView(inner)
    }
}
impl ::core::convert::From<VerificationKeyIDOwnedView>
for ::buffa::OwnedView<VerificationKeyIDView<'static>> {
    fn from(wrapper: VerificationKeyIDOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<VerificationKeyIDView<'static>>>
for VerificationKeyIDOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<VerificationKeyIDView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::VerificationKeyID {
    type View<'a> = VerificationKeyIDView<'a>;
    type ViewHandle = VerificationKeyIDOwnedView;
}
impl ::serde::Serialize for VerificationKeyIDOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
