// @generated by buffa-codegen. DO NOT EDIT.
// source: proto/control_plane/v1/seg.proto

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(i32)]
pub enum SegmentType {
    SEGMENT_TYPE_UNSPECIFIED = 0i32,
    SEGMENT_TYPE_UP = 1i32,
    SEGMENT_TYPE_DOWN = 2i32,
    SEGMENT_TYPE_CORE = 3i32,
}
impl SegmentType {
    ///Idiomatic alias for [`Self::SEGMENT_TYPE_UNSPECIFIED`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Unspecified: Self = Self::SEGMENT_TYPE_UNSPECIFIED;
    ///Idiomatic alias for [`Self::SEGMENT_TYPE_UP`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Up: Self = Self::SEGMENT_TYPE_UP;
    ///Idiomatic alias for [`Self::SEGMENT_TYPE_DOWN`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Down: Self = Self::SEGMENT_TYPE_DOWN;
    ///Idiomatic alias for [`Self::SEGMENT_TYPE_CORE`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Core: Self = Self::SEGMENT_TYPE_CORE;
}
impl ::core::default::Default for SegmentType {
    fn default() -> Self {
        Self::SEGMENT_TYPE_UNSPECIFIED
    }
}
impl ::serde::Serialize for SegmentType {
    fn serialize<S: ::serde::Serializer>(
        &self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        s.serialize_str(::buffa::Enumeration::proto_name(self))
    }
}
impl<'de> ::serde::Deserialize<'de> for SegmentType {
    fn deserialize<D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        struct _V;
        impl ::serde::de::Visitor<'_> for _V {
            type Value = SegmentType;
            fn expecting(
                &self,
                f: &mut ::core::fmt::Formatter<'_>,
            ) -> ::core::fmt::Result {
                f.write_str(
                    concat!("a string, integer, or null for ", stringify!(SegmentType)),
                )
            }
            fn visit_str<E: ::serde::de::Error>(
                self,
                v: &str,
            ) -> ::core::result::Result<SegmentType, E> {
                <SegmentType as ::buffa::Enumeration>::from_proto_name(v)
                    .ok_or_else(|| { ::serde::de::Error::unknown_variant(v, &[]) })
            }
            fn visit_i64<E: ::serde::de::Error>(
                self,
                v: i64,
            ) -> ::core::result::Result<SegmentType, E> {
                let v32 = i32::try_from(v)
                    .map_err(|_| {
                        ::serde::de::Error::custom(
                            ::buffa::alloc::format!("enum value {v} out of i32 range"),
                        )
                    })?;
                <SegmentType as ::buffa::Enumeration>::from_i32(v32)
                    .ok_or_else(|| {
                        ::serde::de::Error::custom(
                            ::buffa::alloc::format!("unknown enum value {v32}"),
                        )
                    })
            }
            fn visit_u64<E: ::serde::de::Error>(
                self,
                v: u64,
            ) -> ::core::result::Result<SegmentType, E> {
                let v32 = i32::try_from(v)
                    .map_err(|_| {
                        ::serde::de::Error::custom(
                            ::buffa::alloc::format!("enum value {v} out of i32 range"),
                        )
                    })?;
                <SegmentType as ::buffa::Enumeration>::from_i32(v32)
                    .ok_or_else(|| {
                        ::serde::de::Error::custom(
                            ::buffa::alloc::format!("unknown enum value {v32}"),
                        )
                    })
            }
            fn visit_unit<E: ::serde::de::Error>(
                self,
            ) -> ::core::result::Result<SegmentType, E> {
                ::core::result::Result::Ok(::core::default::Default::default())
            }
        }
        d.deserialize_any(_V)
    }
}
impl ::buffa::json_helpers::ProtoElemJson for SegmentType {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
impl ::buffa::Enumeration for SegmentType {
    fn from_i32(value: i32) -> ::core::option::Option<Self> {
        match value {
            0i32 => ::core::option::Option::Some(Self::SEGMENT_TYPE_UNSPECIFIED),
            1i32 => ::core::option::Option::Some(Self::SEGMENT_TYPE_UP),
            2i32 => ::core::option::Option::Some(Self::SEGMENT_TYPE_DOWN),
            3i32 => ::core::option::Option::Some(Self::SEGMENT_TYPE_CORE),
            _ => ::core::option::Option::None,
        }
    }
    fn to_i32(&self) -> i32 {
        *self as i32
    }
    fn proto_name(&self) -> &'static str {
        match self {
            Self::SEGMENT_TYPE_UNSPECIFIED => "SEGMENT_TYPE_UNSPECIFIED",
            Self::SEGMENT_TYPE_UP => "SEGMENT_TYPE_UP",
            Self::SEGMENT_TYPE_DOWN => "SEGMENT_TYPE_DOWN",
            Self::SEGMENT_TYPE_CORE => "SEGMENT_TYPE_CORE",
        }
    }
    fn from_proto_name(name: &str) -> ::core::option::Option<Self> {
        match name {
            "SEGMENT_TYPE_UNSPECIFIED" => {
                ::core::option::Option::Some(Self::SEGMENT_TYPE_UNSPECIFIED)
            }
            "SEGMENT_TYPE_UP" => ::core::option::Option::Some(Self::SEGMENT_TYPE_UP),
            "SEGMENT_TYPE_DOWN" => ::core::option::Option::Some(Self::SEGMENT_TYPE_DOWN),
            "SEGMENT_TYPE_CORE" => ::core::option::Option::Some(Self::SEGMENT_TYPE_CORE),
            _ => ::core::option::Option::None,
        }
    }
    fn values() -> &'static [Self] {
        &[
            Self::SEGMENT_TYPE_UNSPECIFIED,
            Self::SEGMENT_TYPE_UP,
            Self::SEGMENT_TYPE_DOWN,
            Self::SEGMENT_TYPE_CORE,
        ]
    }
}
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct SegmentsRequest {
    /// Field 1: `src_isd_as`
    #[serde(
        rename = "srcIsdAs",
        alias = "src_isd_as",
        with = "::buffa::json_helpers::uint64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_u64"
    )]
    pub src_isd_as: u64,
    /// Field 2: `dst_isd_as`
    #[serde(
        rename = "dstIsdAs",
        alias = "dst_isd_as",
        with = "::buffa::json_helpers::uint64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_u64"
    )]
    pub dst_isd_as: u64,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for SegmentsRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("SegmentsRequest")
            .field("src_isd_as", &self.src_isd_as)
            .field("dst_isd_as", &self.dst_isd_as)
            .finish()
    }
}
impl SegmentsRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.SegmentsRequest";
}
::buffa::impl_default_instance!(SegmentsRequest);
impl ::buffa::MessageName for SegmentsRequest {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "SegmentsRequest";
    const FULL_NAME: &'static str = "proto.control_plane.v1.SegmentsRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.SegmentsRequest";
}
impl ::buffa::Message for SegmentsRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.src_isd_as != 0u64 {
            size += 1u32 + ::buffa::types::uint64_encoded_len(self.src_isd_as) as u32;
        }
        if self.dst_isd_as != 0u64 {
            size += 1u32 + ::buffa::types::uint64_encoded_len(self.dst_isd_as) as u32;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.src_isd_as != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.src_isd_as, buf);
        }
        if self.dst_isd_as != 0u64 {
            ::buffa::types::put_uint64_field(2u32, self.dst_isd_as, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.src_isd_as = ::buffa::types::decode_uint64(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.dst_isd_as = ::buffa::types::decode_uint64(buf)?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.src_isd_as = 0u64;
        self.dst_isd_as = 0u64;
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for SegmentsRequest {
    const PROTO_FQN: &'static str = "proto.control_plane.v1.SegmentsRequest";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for SegmentsRequest {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __SEGMENTS_REQUEST_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/proto.control_plane.v1.SegmentsRequest",
    to_json: ::buffa::type_registry::any_to_json::<SegmentsRequest>,
    from_json: ::buffa::type_registry::any_from_json::<SegmentsRequest>,
    is_wkt: false,
};
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct SegmentsResponse {
    /// Field 1: `segments`
    #[serde(
        rename = "segments",
        with = "::buffa::json_helpers::string_key_map",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_map"
    )]
    pub segments: ::buffa::alloc::collections::BTreeMap<
        i32,
        segments_response::Segments,
    >,
    /// Field 1000: `deprecated_signed_revocations`
    #[serde(
        rename = "deprecatedSignedRevocations",
        alias = "deprecated_signed_revocations",
        with = "::buffa::json_helpers::proto_seq",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_vec"
    )]
    pub deprecated_signed_revocations: ::buffa::alloc::vec::Vec<
        ::buffa::alloc::vec::Vec<u8>,
    >,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for SegmentsResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("SegmentsResponse")
            .field("segments", &self.segments)
            .field("deprecated_signed_revocations", &self.deprecated_signed_revocations)
            .finish()
    }
}
impl SegmentsResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.SegmentsResponse";
}
::buffa::impl_default_instance!(SegmentsResponse);
impl ::buffa::MessageName for SegmentsResponse {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "SegmentsResponse";
    const FULL_NAME: &'static str = "proto.control_plane.v1.SegmentsResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.SegmentsResponse";
}
impl ::buffa::Message for SegmentsResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        size
            += ::buffa::map_codec::message_field_len::<
                ::buffa::map_codec::Int32,
                _,
                _,
            >(&self.segments, 1u32, __cache);
        for v in &self.deprecated_signed_revocations {
            size += 2u32 + ::buffa::types::bytes_encoded_len(v) as u32;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        ::buffa::map_codec::write_message_field::<
            ::buffa::map_codec::Int32,
            _,
            _,
        >(&self.segments, 1u32, __cache, buf);
        for v in &self.deprecated_signed_revocations {
            ::buffa::types::put_bytes_field(1000u32, v, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::map_codec::merge_entry::<
                    ::buffa::map_codec::Int32,
                    ::buffa::map_codec::Msg<_>,
                    _,
                >(&mut self.segments, buf, ctx)?;
            }
            1000u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                self.deprecated_signed_revocations
                    .push(::buffa::types::decode_bytes(buf)?);
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        ::buffa::map_codec::MapStorage::storage_clear(&mut self.segments);
        self.deprecated_signed_revocations.clear();
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for SegmentsResponse {
    const PROTO_FQN: &'static str = "proto.control_plane.v1.SegmentsResponse";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for SegmentsResponse {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __SEGMENTS_RESPONSE_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/proto.control_plane.v1.SegmentsResponse",
    to_json: ::buffa::type_registry::any_to_json::<SegmentsResponse>,
    from_json: ::buffa::type_registry::any_from_json::<SegmentsResponse>,
    is_wkt: false,
};
pub mod segments_response {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Default)]
    #[derive(::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Segments {
        /// Field 1: `segments`
        #[serde(
            rename = "segments",
            skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_vec",
            deserialize_with = "::buffa::json_helpers::null_as_default"
        )]
        pub segments: ::buffa::alloc::vec::Vec<super::PathSegment>,
        #[serde(skip)]
        #[doc(hidden)]
        pub __buffa_unknown_fields: ::buffa::UnknownFields,
    }
    impl ::core::fmt::Debug for Segments {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("Segments").field("segments", &self.segments).finish()
        }
    }
    impl Segments {
        /// Protobuf type URL for this message, for use with `Any::pack` and
        /// `Any::unpack_if`.
        ///
        /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
        pub const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.SegmentsResponse.Segments";
    }
    ::buffa::impl_default_instance!(Segments);
    impl ::buffa::MessageName for Segments {
        const PACKAGE: &'static str = "proto.control_plane.v1";
        const NAME: &'static str = "SegmentsResponse.Segments";
        const FULL_NAME: &'static str = "proto.control_plane.v1.SegmentsResponse.Segments";
        const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.SegmentsResponse.Segments";
    }
    impl ::buffa::Message for Segments {
        /// Returns the total encoded size in bytes.
        ///
        /// The result is a `u32`; the protobuf specification requires all
        /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
        /// compliant message will never overflow this type.
        #[allow(clippy::let_and_return)]
        fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
            #[allow(unused_imports)]
            use ::buffa::Enumeration as _;
            let mut size = 0u32;
            for v in &self.segments {
                let __slot = __cache.reserve();
                let inner_size = v.compute_size(__cache);
                __cache.set(__slot, inner_size);
                size
                    += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                        + inner_size;
            }
            size += self.__buffa_unknown_fields.encoded_len() as u32;
            size
        }
        fn write_to(
            &self,
            __cache: &mut ::buffa::SizeCache,
            buf: &mut impl ::buffa::bytes::BufMut,
        ) {
            #[allow(unused_imports)]
            use ::buffa::Enumeration as _;
            for v in &self.segments {
                ::buffa::types::put_len_delimited_header(
                    1u32,
                    __cache.consume_next(),
                    buf,
                );
                v.write_to(__cache, buf);
            }
            self.__buffa_unknown_fields.write_to(buf);
        }
        fn merge_field(
            &mut self,
            tag: ::buffa::encoding::Tag,
            buf: &mut impl ::buffa::bytes::Buf,
            ctx: ::buffa::DecodeContext<'_>,
        ) -> ::core::result::Result<(), ::buffa::DecodeError> {
            #[allow(unused_imports)]
            use ::buffa::bytes::Buf as _;
            #[allow(unused_imports)]
            use ::buffa::Enumeration as _;
            match tag.field_number() {
                1u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    let mut elem = ::core::default::Default::default();
                    ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                    self.segments.push(elem);
                }
                _ => {
                    self.__buffa_unknown_fields
                        .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
                }
            }
            ::core::result::Result::Ok(())
        }
        fn clear(&mut self) {
            self.segments.clear();
            self.__buffa_unknown_fields.clear();
        }
    }
    impl ::buffa::ExtensionSet for Segments {
        const PROTO_FQN: &'static str = "proto.control_plane.v1.SegmentsResponse.Segments";
        fn unknown_fields(&self) -> &::buffa::UnknownFields {
            &self.__buffa_unknown_fields
        }
        fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
            &mut self.__buffa_unknown_fields
        }
    }
    impl ::buffa::json_helpers::ProtoElemJson for Segments {
        fn serialize_proto_json<S: ::serde::Serializer>(
            v: &Self,
            s: S,
        ) -> ::core::result::Result<S::Ok, S::Error> {
            ::serde::Serialize::serialize(v, s)
        }
        fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
            d: D,
        ) -> ::core::result::Result<Self, D::Error> {
            <Self as ::serde::Deserialize>::deserialize(d)
        }
    }
    #[doc(hidden)]
    pub const __SEGMENTS_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
        type_url: "type.googleapis.com/proto.control_plane.v1.SegmentsResponse.Segments",
        to_json: ::buffa::type_registry::any_to_json::<Segments>,
        from_json: ::buffa::type_registry::any_from_json::<Segments>,
        is_wkt: false,
    };
    #[doc(inline)]
    pub use super::__buffa::view::segments_response::SegmentsView;
    #[doc(inline)]
    pub use super::__buffa::view::segments_response::SegmentsOwnedView;
}
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct SegmentsRegistrationRequest {
    /// Field 1: `segments`
    #[serde(
        rename = "segments",
        with = "::buffa::json_helpers::string_key_map",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_map"
    )]
    pub segments: ::buffa::alloc::collections::BTreeMap<
        i32,
        segments_registration_request::Segments,
    >,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for SegmentsRegistrationRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("SegmentsRegistrationRequest")
            .field("segments", &self.segments)
            .finish()
    }
}
impl SegmentsRegistrationRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.SegmentsRegistrationRequest";
}
::buffa::impl_default_instance!(SegmentsRegistrationRequest);
impl ::buffa::MessageName for SegmentsRegistrationRequest {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "SegmentsRegistrationRequest";
    const FULL_NAME: &'static str = "proto.control_plane.v1.SegmentsRegistrationRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.SegmentsRegistrationRequest";
}
impl ::buffa::Message for SegmentsRegistrationRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        size
            += ::buffa::map_codec::message_field_len::<
                ::buffa::map_codec::Int32,
                _,
                _,
            >(&self.segments, 1u32, __cache);
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        ::buffa::map_codec::write_message_field::<
            ::buffa::map_codec::Int32,
            _,
            _,
        >(&self.segments, 1u32, __cache, buf);
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::map_codec::merge_entry::<
                    ::buffa::map_codec::Int32,
                    ::buffa::map_codec::Msg<_>,
                    _,
                >(&mut self.segments, buf, ctx)?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        ::buffa::map_codec::MapStorage::storage_clear(&mut self.segments);
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for SegmentsRegistrationRequest {
    const PROTO_FQN: &'static str = "proto.control_plane.v1.SegmentsRegistrationRequest";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for SegmentsRegistrationRequest {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __SEGMENTS_REGISTRATION_REQUEST_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/proto.control_plane.v1.SegmentsRegistrationRequest",
    to_json: ::buffa::type_registry::any_to_json::<SegmentsRegistrationRequest>,
    from_json: ::buffa::type_registry::any_from_json::<SegmentsRegistrationRequest>,
    is_wkt: false,
};
pub mod segments_registration_request {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Default)]
    #[derive(::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Segments {
        /// Field 1: `segments`
        #[serde(
            rename = "segments",
            skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_vec",
            deserialize_with = "::buffa::json_helpers::null_as_default"
        )]
        pub segments: ::buffa::alloc::vec::Vec<super::PathSegment>,
        #[serde(skip)]
        #[doc(hidden)]
        pub __buffa_unknown_fields: ::buffa::UnknownFields,
    }
    impl ::core::fmt::Debug for Segments {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("Segments").field("segments", &self.segments).finish()
        }
    }
    impl Segments {
        /// Protobuf type URL for this message, for use with `Any::pack` and
        /// `Any::unpack_if`.
        ///
        /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
        pub const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.SegmentsRegistrationRequest.Segments";
    }
    ::buffa::impl_default_instance!(Segments);
    impl ::buffa::MessageName for Segments {
        const PACKAGE: &'static str = "proto.control_plane.v1";
        const NAME: &'static str = "SegmentsRegistrationRequest.Segments";
        const FULL_NAME: &'static str = "proto.control_plane.v1.SegmentsRegistrationRequest.Segments";
        const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.SegmentsRegistrationRequest.Segments";
    }
    impl ::buffa::Message for Segments {
        /// Returns the total encoded size in bytes.
        ///
        /// The result is a `u32`; the protobuf specification requires all
        /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
        /// compliant message will never overflow this type.
        #[allow(clippy::let_and_return)]
        fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
            #[allow(unused_imports)]
            use ::buffa::Enumeration as _;
            let mut size = 0u32;
            for v in &self.segments {
                let __slot = __cache.reserve();
                let inner_size = v.compute_size(__cache);
                __cache.set(__slot, inner_size);
                size
                    += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                        + inner_size;
            }
            size += self.__buffa_unknown_fields.encoded_len() as u32;
            size
        }
        fn write_to(
            &self,
            __cache: &mut ::buffa::SizeCache,
            buf: &mut impl ::buffa::bytes::BufMut,
        ) {
            #[allow(unused_imports)]
            use ::buffa::Enumeration as _;
            for v in &self.segments {
                ::buffa::types::put_len_delimited_header(
                    1u32,
                    __cache.consume_next(),
                    buf,
                );
                v.write_to(__cache, buf);
            }
            self.__buffa_unknown_fields.write_to(buf);
        }
        fn merge_field(
            &mut self,
            tag: ::buffa::encoding::Tag,
            buf: &mut impl ::buffa::bytes::Buf,
            ctx: ::buffa::DecodeContext<'_>,
        ) -> ::core::result::Result<(), ::buffa::DecodeError> {
            #[allow(unused_imports)]
            use ::buffa::bytes::Buf as _;
            #[allow(unused_imports)]
            use ::buffa::Enumeration as _;
            match tag.field_number() {
                1u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    let mut elem = ::core::default::Default::default();
                    ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                    self.segments.push(elem);
                }
                _ => {
                    self.__buffa_unknown_fields
                        .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
                }
            }
            ::core::result::Result::Ok(())
        }
        fn clear(&mut self) {
            self.segments.clear();
            self.__buffa_unknown_fields.clear();
        }
    }
    impl ::buffa::ExtensionSet for Segments {
        const PROTO_FQN: &'static str = "proto.control_plane.v1.SegmentsRegistrationRequest.Segments";
        fn unknown_fields(&self) -> &::buffa::UnknownFields {
            &self.__buffa_unknown_fields
        }
        fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
            &mut self.__buffa_unknown_fields
        }
    }
    impl ::buffa::json_helpers::ProtoElemJson for Segments {
        fn serialize_proto_json<S: ::serde::Serializer>(
            v: &Self,
            s: S,
        ) -> ::core::result::Result<S::Ok, S::Error> {
            ::serde::Serialize::serialize(v, s)
        }
        fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
            d: D,
        ) -> ::core::result::Result<Self, D::Error> {
            <Self as ::serde::Deserialize>::deserialize(d)
        }
    }
    #[doc(hidden)]
    pub const __SEGMENTS_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
        type_url: "type.googleapis.com/proto.control_plane.v1.SegmentsRegistrationRequest.Segments",
        to_json: ::buffa::type_registry::any_to_json::<Segments>,
        from_json: ::buffa::type_registry::any_from_json::<Segments>,
        is_wkt: false,
    };
    #[doc(inline)]
    pub use super::__buffa::view::segments_registration_request::SegmentsView;
    #[doc(inline)]
    pub use super::__buffa::view::segments_registration_request::SegmentsOwnedView;
}
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct SegmentsRegistrationResponse {
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for SegmentsRegistrationResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("SegmentsRegistrationResponse").finish()
    }
}
impl SegmentsRegistrationResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.SegmentsRegistrationResponse";
}
::buffa::impl_default_instance!(SegmentsRegistrationResponse);
impl ::buffa::MessageName for SegmentsRegistrationResponse {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "SegmentsRegistrationResponse";
    const FULL_NAME: &'static str = "proto.control_plane.v1.SegmentsRegistrationResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.SegmentsRegistrationResponse";
}
impl ::buffa::Message for SegmentsRegistrationResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for SegmentsRegistrationResponse {
    const PROTO_FQN: &'static str = "proto.control_plane.v1.SegmentsRegistrationResponse";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for SegmentsRegistrationResponse {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __SEGMENTS_REGISTRATION_RESPONSE_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/proto.control_plane.v1.SegmentsRegistrationResponse",
    to_json: ::buffa::type_registry::any_to_json::<SegmentsRegistrationResponse>,
    from_json: ::buffa::type_registry::any_from_json::<SegmentsRegistrationResponse>,
    is_wkt: false,
};
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct BeaconRequest {
    /// Field 1: `segment`
    #[serde(
        rename = "segment",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_unset_message_field"
    )]
    pub segment: ::buffa::MessageField<PathSegment>,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for BeaconRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("BeaconRequest").field("segment", &self.segment).finish()
    }
}
impl BeaconRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.BeaconRequest";
}
::buffa::impl_default_instance!(BeaconRequest);
impl ::buffa::MessageName for BeaconRequest {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "BeaconRequest";
    const FULL_NAME: &'static str = "proto.control_plane.v1.BeaconRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.BeaconRequest";
}
impl ::buffa::Message for BeaconRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.segment.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.segment.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.segment.is_set() {
            ::buffa::types::put_len_delimited_header(1u32, __cache.consume_next(), buf);
            self.segment.write_to(__cache, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.segment.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.segment = ::buffa::MessageField::none();
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for BeaconRequest {
    const PROTO_FQN: &'static str = "proto.control_plane.v1.BeaconRequest";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for BeaconRequest {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __BEACON_REQUEST_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/proto.control_plane.v1.BeaconRequest",
    to_json: ::buffa::type_registry::any_to_json::<BeaconRequest>,
    from_json: ::buffa::type_registry::any_from_json::<BeaconRequest>,
    is_wkt: false,
};
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct BeaconResponse {
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for BeaconResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("BeaconResponse").finish()
    }
}
impl BeaconResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.BeaconResponse";
}
::buffa::impl_default_instance!(BeaconResponse);
impl ::buffa::MessageName for BeaconResponse {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "BeaconResponse";
    const FULL_NAME: &'static str = "proto.control_plane.v1.BeaconResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.BeaconResponse";
}
impl ::buffa::Message for BeaconResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for BeaconResponse {
    const PROTO_FQN: &'static str = "proto.control_plane.v1.BeaconResponse";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for BeaconResponse {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __BEACON_RESPONSE_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/proto.control_plane.v1.BeaconResponse",
    to_json: ::buffa::type_registry::any_to_json::<BeaconResponse>,
    from_json: ::buffa::type_registry::any_from_json::<BeaconResponse>,
    is_wkt: false,
};
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct PathSegment {
    /// Field 1: `segment_info`
    #[serde(
        rename = "segmentInfo",
        alias = "segment_info",
        with = "::buffa::json_helpers::bytes",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_bytes"
    )]
    pub segment_info: ::buffa::alloc::vec::Vec<u8>,
    /// Field 2: `as_entries`
    #[serde(
        rename = "asEntries",
        alias = "as_entries",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_vec",
        deserialize_with = "::buffa::json_helpers::null_as_default"
    )]
    pub as_entries: ::buffa::alloc::vec::Vec<ASEntry>,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for PathSegment {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("PathSegment")
            .field("segment_info", &self.segment_info)
            .field("as_entries", &self.as_entries)
            .finish()
    }
}
impl PathSegment {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.PathSegment";
}
::buffa::impl_default_instance!(PathSegment);
impl ::buffa::MessageName for PathSegment {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "PathSegment";
    const FULL_NAME: &'static str = "proto.control_plane.v1.PathSegment";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.PathSegment";
}
impl ::buffa::Message for PathSegment {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.segment_info.is_empty() {
            size += 1u32 + ::buffa::types::bytes_encoded_len(&self.segment_info) as u32;
        }
        for v in &self.as_entries {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.segment_info.is_empty() {
            ::buffa::types::put_bytes_field(1u32, &self.segment_info, buf);
        }
        for v in &self.as_entries {
            ::buffa::types::put_len_delimited_header(2u32, __cache.consume_next(), buf);
            v.write_to(__cache, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.segment_info, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.as_entries.push(elem);
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.segment_info.clear();
        self.as_entries.clear();
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for PathSegment {
    const PROTO_FQN: &'static str = "proto.control_plane.v1.PathSegment";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for PathSegment {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __PATH_SEGMENT_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/proto.control_plane.v1.PathSegment",
    to_json: ::buffa::type_registry::any_to_json::<PathSegment>,
    from_json: ::buffa::type_registry::any_from_json::<PathSegment>,
    is_wkt: false,
};
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct SegmentInformation {
    /// Field 1: `timestamp`
    #[serde(
        rename = "timestamp",
        with = "::buffa::json_helpers::int64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_i64"
    )]
    pub timestamp: i64,
    /// Field 2: `segment_id`
    #[serde(
        rename = "segmentId",
        alias = "segment_id",
        with = "::buffa::json_helpers::uint32",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_u32"
    )]
    pub segment_id: u32,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for SegmentInformation {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("SegmentInformation")
            .field("timestamp", &self.timestamp)
            .field("segment_id", &self.segment_id)
            .finish()
    }
}
impl SegmentInformation {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.SegmentInformation";
}
::buffa::impl_default_instance!(SegmentInformation);
impl ::buffa::MessageName for SegmentInformation {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "SegmentInformation";
    const FULL_NAME: &'static str = "proto.control_plane.v1.SegmentInformation";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.SegmentInformation";
}
impl ::buffa::Message for SegmentInformation {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.timestamp != 0i64 {
            size += 1u32 + ::buffa::types::int64_encoded_len(self.timestamp) as u32;
        }
        if self.segment_id != 0u32 {
            size += 1u32 + ::buffa::types::uint32_encoded_len(self.segment_id) as u32;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.timestamp != 0i64 {
            ::buffa::types::put_int64_field(1u32, self.timestamp, buf);
        }
        if self.segment_id != 0u32 {
            ::buffa::types::put_uint32_field(2u32, self.segment_id, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.timestamp = ::buffa::types::decode_int64(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.segment_id = ::buffa::types::decode_uint32(buf)?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.timestamp = 0i64;
        self.segment_id = 0u32;
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for SegmentInformation {
    const PROTO_FQN: &'static str = "proto.control_plane.v1.SegmentInformation";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for SegmentInformation {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __SEGMENT_INFORMATION_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/proto.control_plane.v1.SegmentInformation",
    to_json: ::buffa::type_registry::any_to_json::<SegmentInformation>,
    from_json: ::buffa::type_registry::any_from_json::<SegmentInformation>,
    is_wkt: false,
};
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct ASEntry {
    /// Field 1: `signed`
    #[serde(
        rename = "signed",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_unset_message_field"
    )]
    pub signed: ::buffa::MessageField<super::super::crypto::v1::SignedMessage>,
    /// Field 2: `unsigned`
    #[serde(
        rename = "unsigned",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_unset_message_field"
    )]
    pub unsigned: ::buffa::MessageField<PathSegmentUnsignedExtensions>,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for ASEntry {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("ASEntry")
            .field("signed", &self.signed)
            .field("unsigned", &self.unsigned)
            .finish()
    }
}
impl ASEntry {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.ASEntry";
}
::buffa::impl_default_instance!(ASEntry);
impl ::buffa::MessageName for ASEntry {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "ASEntry";
    const FULL_NAME: &'static str = "proto.control_plane.v1.ASEntry";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.ASEntry";
}
impl ::buffa::Message for ASEntry {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.signed.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.signed.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        if self.unsigned.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.unsigned.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.signed.is_set() {
            ::buffa::types::put_len_delimited_header(1u32, __cache.consume_next(), buf);
            self.signed.write_to(__cache, buf);
        }
        if self.unsigned.is_set() {
            ::buffa::types::put_len_delimited_header(2u32, __cache.consume_next(), buf);
            self.unsigned.write_to(__cache, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.signed.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.unsigned.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.signed = ::buffa::MessageField::none();
        self.unsigned = ::buffa::MessageField::none();
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for ASEntry {
    const PROTO_FQN: &'static str = "proto.control_plane.v1.ASEntry";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for ASEntry {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __AS_ENTRY_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/proto.control_plane.v1.ASEntry",
    to_json: ::buffa::type_registry::any_to_json::<ASEntry>,
    from_json: ::buffa::type_registry::any_from_json::<ASEntry>,
    is_wkt: false,
};
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct ASEntrySignedBody {
    /// Field 1: `isd_as`
    #[serde(
        rename = "isdAs",
        alias = "isd_as",
        with = "::buffa::json_helpers::uint64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_u64"
    )]
    pub isd_as: u64,
    /// Field 2: `next_isd_as`
    #[serde(
        rename = "nextIsdAs",
        alias = "next_isd_as",
        with = "::buffa::json_helpers::uint64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_u64"
    )]
    pub next_isd_as: u64,
    /// Field 3: `hop_entry`
    #[serde(
        rename = "hopEntry",
        alias = "hop_entry",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_unset_message_field"
    )]
    pub hop_entry: ::buffa::MessageField<HopEntry>,
    /// Field 4: `peer_entries`
    #[serde(
        rename = "peerEntries",
        alias = "peer_entries",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_vec",
        deserialize_with = "::buffa::json_helpers::null_as_default"
    )]
    pub peer_entries: ::buffa::alloc::vec::Vec<PeerEntry>,
    /// Field 5: `mtu`
    #[serde(
        rename = "mtu",
        with = "::buffa::json_helpers::uint32",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_u32"
    )]
    pub mtu: u32,
    /// Field 6: `extensions`
    #[serde(
        rename = "extensions",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_unset_message_field"
    )]
    pub extensions: ::buffa::MessageField<PathSegmentExtensions>,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for ASEntrySignedBody {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("ASEntrySignedBody")
            .field("isd_as", &self.isd_as)
            .field("next_isd_as", &self.next_isd_as)
            .field("hop_entry", &self.hop_entry)
            .field("peer_entries", &self.peer_entries)
            .field("mtu", &self.mtu)
            .field("extensions", &self.extensions)
            .finish()
    }
}
impl ASEntrySignedBody {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.ASEntrySignedBody";
}
::buffa::impl_default_instance!(ASEntrySignedBody);
impl ::buffa::MessageName for ASEntrySignedBody {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "ASEntrySignedBody";
    const FULL_NAME: &'static str = "proto.control_plane.v1.ASEntrySignedBody";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.ASEntrySignedBody";
}
impl ::buffa::Message for ASEntrySignedBody {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.isd_as != 0u64 {
            size += 1u32 + ::buffa::types::uint64_encoded_len(self.isd_as) as u32;
        }
        if self.next_isd_as != 0u64 {
            size += 1u32 + ::buffa::types::uint64_encoded_len(self.next_isd_as) as u32;
        }
        if self.hop_entry.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.hop_entry.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        for v in &self.peer_entries {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        if self.mtu != 0u32 {
            size += 1u32 + ::buffa::types::uint32_encoded_len(self.mtu) as u32;
        }
        if self.extensions.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.extensions.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.isd_as != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.isd_as, buf);
        }
        if self.next_isd_as != 0u64 {
            ::buffa::types::put_uint64_field(2u32, self.next_isd_as, buf);
        }
        if self.hop_entry.is_set() {
            ::buffa::types::put_len_delimited_header(3u32, __cache.consume_next(), buf);
            self.hop_entry.write_to(__cache, buf);
        }
        for v in &self.peer_entries {
            ::buffa::types::put_len_delimited_header(4u32, __cache.consume_next(), buf);
            v.write_to(__cache, buf);
        }
        if self.mtu != 0u32 {
            ::buffa::types::put_uint32_field(5u32, self.mtu, buf);
        }
        if self.extensions.is_set() {
            ::buffa::types::put_len_delimited_header(6u32, __cache.consume_next(), buf);
            self.extensions.write_to(__cache, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.isd_as = ::buffa::types::decode_uint64(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.next_isd_as = ::buffa::types::decode_uint64(buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.hop_entry.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.peer_entries.push(elem);
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.mtu = ::buffa::types::decode_uint32(buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.extensions.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.isd_as = 0u64;
        self.next_isd_as = 0u64;
        self.hop_entry = ::buffa::MessageField::none();
        self.peer_entries.clear();
        self.mtu = 0u32;
        self.extensions = ::buffa::MessageField::none();
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for ASEntrySignedBody {
    const PROTO_FQN: &'static str = "proto.control_plane.v1.ASEntrySignedBody";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for ASEntrySignedBody {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __AS_ENTRY_SIGNED_BODY_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/proto.control_plane.v1.ASEntrySignedBody",
    to_json: ::buffa::type_registry::any_to_json::<ASEntrySignedBody>,
    from_json: ::buffa::type_registry::any_from_json::<ASEntrySignedBody>,
    is_wkt: false,
};
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct HopEntry {
    /// Field 1: `hop_field`
    #[serde(
        rename = "hopField",
        alias = "hop_field",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_unset_message_field"
    )]
    pub hop_field: ::buffa::MessageField<HopField>,
    /// Field 2: `ingress_mtu`
    #[serde(
        rename = "ingressMtu",
        alias = "ingress_mtu",
        with = "::buffa::json_helpers::uint32",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_u32"
    )]
    pub ingress_mtu: u32,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for HopEntry {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("HopEntry")
            .field("hop_field", &self.hop_field)
            .field("ingress_mtu", &self.ingress_mtu)
            .finish()
    }
}
impl HopEntry {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.HopEntry";
}
::buffa::impl_default_instance!(HopEntry);
impl ::buffa::MessageName for HopEntry {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "HopEntry";
    const FULL_NAME: &'static str = "proto.control_plane.v1.HopEntry";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.HopEntry";
}
impl ::buffa::Message for HopEntry {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.hop_field.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.hop_field.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        if self.ingress_mtu != 0u32 {
            size += 1u32 + ::buffa::types::uint32_encoded_len(self.ingress_mtu) as u32;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.hop_field.is_set() {
            ::buffa::types::put_len_delimited_header(1u32, __cache.consume_next(), buf);
            self.hop_field.write_to(__cache, buf);
        }
        if self.ingress_mtu != 0u32 {
            ::buffa::types::put_uint32_field(2u32, self.ingress_mtu, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.hop_field.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.ingress_mtu = ::buffa::types::decode_uint32(buf)?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.hop_field = ::buffa::MessageField::none();
        self.ingress_mtu = 0u32;
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for HopEntry {
    const PROTO_FQN: &'static str = "proto.control_plane.v1.HopEntry";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for HopEntry {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __HOP_ENTRY_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/proto.control_plane.v1.HopEntry",
    to_json: ::buffa::type_registry::any_to_json::<HopEntry>,
    from_json: ::buffa::type_registry::any_from_json::<HopEntry>,
    is_wkt: false,
};
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct PeerEntry {
    /// Field 1: `peer_isd_as`
    #[serde(
        rename = "peerIsdAs",
        alias = "peer_isd_as",
        with = "::buffa::json_helpers::uint64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_u64"
    )]
    pub peer_isd_as: u64,
    /// Field 2: `peer_interface`
    #[serde(
        rename = "peerInterface",
        alias = "peer_interface",
        with = "::buffa::json_helpers::uint64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_u64"
    )]
    pub peer_interface: u64,
    /// Field 3: `peer_mtu`
    #[serde(
        rename = "peerMtu",
        alias = "peer_mtu",
        with = "::buffa::json_helpers::uint32",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_u32"
    )]
    pub peer_mtu: u32,
    /// Field 4: `hop_field`
    #[serde(
        rename = "hopField",
        alias = "hop_field",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_unset_message_field"
    )]
    pub hop_field: ::buffa::MessageField<HopField>,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for PeerEntry {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("PeerEntry")
            .field("peer_isd_as", &self.peer_isd_as)
            .field("peer_interface", &self.peer_interface)
            .field("peer_mtu", &self.peer_mtu)
            .field("hop_field", &self.hop_field)
            .finish()
    }
}
impl PeerEntry {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.PeerEntry";
}
::buffa::impl_default_instance!(PeerEntry);
impl ::buffa::MessageName for PeerEntry {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "PeerEntry";
    const FULL_NAME: &'static str = "proto.control_plane.v1.PeerEntry";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.PeerEntry";
}
impl ::buffa::Message for PeerEntry {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.peer_isd_as != 0u64 {
            size += 1u32 + ::buffa::types::uint64_encoded_len(self.peer_isd_as) as u32;
        }
        if self.peer_interface != 0u64 {
            size
                += 1u32 + ::buffa::types::uint64_encoded_len(self.peer_interface) as u32;
        }
        if self.peer_mtu != 0u32 {
            size += 1u32 + ::buffa::types::uint32_encoded_len(self.peer_mtu) as u32;
        }
        if self.hop_field.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.hop_field.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.peer_isd_as != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.peer_isd_as, buf);
        }
        if self.peer_interface != 0u64 {
            ::buffa::types::put_uint64_field(2u32, self.peer_interface, buf);
        }
        if self.peer_mtu != 0u32 {
            ::buffa::types::put_uint32_field(3u32, self.peer_mtu, buf);
        }
        if self.hop_field.is_set() {
            ::buffa::types::put_len_delimited_header(4u32, __cache.consume_next(), buf);
            self.hop_field.write_to(__cache, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.peer_isd_as = ::buffa::types::decode_uint64(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.peer_interface = ::buffa::types::decode_uint64(buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.peer_mtu = ::buffa::types::decode_uint32(buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.hop_field.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.peer_isd_as = 0u64;
        self.peer_interface = 0u64;
        self.peer_mtu = 0u32;
        self.hop_field = ::buffa::MessageField::none();
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for PeerEntry {
    const PROTO_FQN: &'static str = "proto.control_plane.v1.PeerEntry";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for PeerEntry {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __PEER_ENTRY_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/proto.control_plane.v1.PeerEntry",
    to_json: ::buffa::type_registry::any_to_json::<PeerEntry>,
    from_json: ::buffa::type_registry::any_from_json::<PeerEntry>,
    is_wkt: false,
};
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct HopField {
    /// Field 1: `ingress`
    #[serde(
        rename = "ingress",
        with = "::buffa::json_helpers::uint64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_u64"
    )]
    pub ingress: u64,
    /// Field 2: `egress`
    #[serde(
        rename = "egress",
        with = "::buffa::json_helpers::uint64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_u64"
    )]
    pub egress: u64,
    /// Field 3: `exp_time`
    #[serde(
        rename = "expTime",
        alias = "exp_time",
        with = "::buffa::json_helpers::uint32",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_u32"
    )]
    pub exp_time: u32,
    /// Field 4: `mac`
    #[serde(
        rename = "mac",
        with = "::buffa::json_helpers::bytes",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_bytes"
    )]
    pub mac: ::buffa::alloc::vec::Vec<u8>,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for HopField {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("HopField")
            .field("ingress", &self.ingress)
            .field("egress", &self.egress)
            .field("exp_time", &self.exp_time)
            .field("mac", &self.mac)
            .finish()
    }
}
impl HopField {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.HopField";
}
::buffa::impl_default_instance!(HopField);
impl ::buffa::MessageName for HopField {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "HopField";
    const FULL_NAME: &'static str = "proto.control_plane.v1.HopField";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.HopField";
}
impl ::buffa::Message for HopField {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.ingress != 0u64 {
            size += 1u32 + ::buffa::types::uint64_encoded_len(self.ingress) as u32;
        }
        if self.egress != 0u64 {
            size += 1u32 + ::buffa::types::uint64_encoded_len(self.egress) as u32;
        }
        if self.exp_time != 0u32 {
            size += 1u32 + ::buffa::types::uint32_encoded_len(self.exp_time) as u32;
        }
        if !self.mac.is_empty() {
            size += 1u32 + ::buffa::types::bytes_encoded_len(&self.mac) as u32;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.ingress != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.ingress, buf);
        }
        if self.egress != 0u64 {
            ::buffa::types::put_uint64_field(2u32, self.egress, buf);
        }
        if self.exp_time != 0u32 {
            ::buffa::types::put_uint32_field(3u32, self.exp_time, buf);
        }
        if !self.mac.is_empty() {
            ::buffa::types::put_bytes_field(4u32, &self.mac, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.ingress = ::buffa::types::decode_uint64(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.egress = ::buffa::types::decode_uint64(buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.exp_time = ::buffa::types::decode_uint32(buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.mac, buf)?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.ingress = 0u64;
        self.egress = 0u64;
        self.exp_time = 0u32;
        self.mac.clear();
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for HopField {
    const PROTO_FQN: &'static str = "proto.control_plane.v1.HopField";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for HopField {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __HOP_FIELD_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/proto.control_plane.v1.HopField",
    to_json: ::buffa::type_registry::any_to_json::<HopField>,
    from_json: ::buffa::type_registry::any_from_json::<HopField>,
    is_wkt: false,
};
