// @generated by buffa-codegen. DO NOT EDIT.

include!("proto.daemon.v1.daemon.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("proto.daemon.v1.daemon.__view.rs");
    }
    /// Register this package's `Any` type entries and extension entries.
    pub fn register_types(reg: &mut ::buffa::type_registry::TypeRegistry) {
        reg.register_json_any(super::__PATHS_REQUEST_JSON_ANY);
        reg.register_json_any(super::__PATHS_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__PATH_JSON_ANY);
        reg.register_json_any(super::__DISCOVERY_INFORMATION_JSON_ANY);
        reg.register_json_any(super::__EPIC_AUTHS_JSON_ANY);
        reg.register_json_any(super::__PATH_INTERFACE_JSON_ANY);
        reg.register_json_any(super::__GEO_COORDINATES_JSON_ANY);
        reg.register_json_any(super::__AS_REQUEST_JSON_ANY);
        reg.register_json_any(super::__AS_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__INTERFACES_REQUEST_JSON_ANY);
        reg.register_json_any(super::__INTERFACES_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__INTERFACE_JSON_ANY);
        reg.register_json_any(super::__SERVICES_REQUEST_JSON_ANY);
        reg.register_json_any(super::__SERVICES_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__LIST_SERVICE_JSON_ANY);
        reg.register_json_any(super::__SERVICE_JSON_ANY);
        reg.register_json_any(super::__UNDERLAY_JSON_ANY);
        reg.register_json_any(super::__NOTIFY_INTERFACE_DOWN_REQUEST_JSON_ANY);
        reg.register_json_any(super::__NOTIFY_INTERFACE_DOWN_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__PORT_RANGE_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_HOST_AS_REQUEST_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_HOST_AS_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_AS_HOST_REQUEST_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_AS_HOST_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_HOST_HOST_REQUEST_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_HOST_HOST_RESPONSE_JSON_ANY);
    }
}
#[doc(inline)]
pub use self::__buffa::view::PathsRequestView;
#[doc(inline)]
pub use self::__buffa::view::PathsRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::PathsResponseView;
#[doc(inline)]
pub use self::__buffa::view::PathsResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::PathView;
#[doc(inline)]
pub use self::__buffa::view::PathOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DiscoveryInformationView;
#[doc(inline)]
pub use self::__buffa::view::DiscoveryInformationOwnedView;
#[doc(inline)]
pub use self::__buffa::view::EpicAuthsView;
#[doc(inline)]
pub use self::__buffa::view::EpicAuthsOwnedView;
#[doc(inline)]
pub use self::__buffa::view::PathInterfaceView;
#[doc(inline)]
pub use self::__buffa::view::PathInterfaceOwnedView;
#[doc(inline)]
pub use self::__buffa::view::GeoCoordinatesView;
#[doc(inline)]
pub use self::__buffa::view::GeoCoordinatesOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ASRequestView;
#[doc(inline)]
pub use self::__buffa::view::ASRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ASResponseView;
#[doc(inline)]
pub use self::__buffa::view::ASResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::InterfacesRequestView;
#[doc(inline)]
pub use self::__buffa::view::InterfacesRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::InterfacesResponseView;
#[doc(inline)]
pub use self::__buffa::view::InterfacesResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::InterfaceView;
#[doc(inline)]
pub use self::__buffa::view::InterfaceOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ServicesRequestView;
#[doc(inline)]
pub use self::__buffa::view::ServicesRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ServicesResponseView;
#[doc(inline)]
pub use self::__buffa::view::ServicesResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ListServiceView;
#[doc(inline)]
pub use self::__buffa::view::ListServiceOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ServiceView;
#[doc(inline)]
pub use self::__buffa::view::ServiceOwnedView;
#[doc(inline)]
pub use self::__buffa::view::UnderlayView;
#[doc(inline)]
pub use self::__buffa::view::UnderlayOwnedView;
#[doc(inline)]
pub use self::__buffa::view::NotifyInterfaceDownRequestView;
#[doc(inline)]
pub use self::__buffa::view::NotifyInterfaceDownRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::NotifyInterfaceDownResponseView;
#[doc(inline)]
pub use self::__buffa::view::NotifyInterfaceDownResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::PortRangeResponseView;
#[doc(inline)]
pub use self::__buffa::view::PortRangeResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyHostASRequestView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyHostASRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyHostASResponseView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyHostASResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyASHostRequestView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyASHostRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyASHostResponseView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyASHostResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyHostHostRequestView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyHostHostRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyHostHostResponseView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyHostHostResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::register_types;
include!("proto.daemon.v1.daemon.__connect.rs");
