// @generated by buffa-codegen. DO NOT EDIT.

include!("proto.control_plane.v1.cppki.rs");
include!("proto.control_plane.v1.drkey.rs");
include!("proto.control_plane.v1.renewal.rs");
include!("proto.control_plane.v1.seg.rs");
include!("proto.control_plane.v1.seg_extensions.rs");
include!("proto.control_plane.v1.svc_resolution.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("proto.control_plane.v1.cppki.__view.rs");
        include!("proto.control_plane.v1.drkey.__view.rs");
        include!("proto.control_plane.v1.renewal.__view.rs");
        include!("proto.control_plane.v1.seg.__view.rs");
        include!("proto.control_plane.v1.seg_extensions.__view.rs");
        include!("proto.control_plane.v1.svc_resolution.__view.rs");
    }
    /// Register this package's `Any` type entries and extension entries.
    pub fn register_types(reg: &mut ::buffa::type_registry::TypeRegistry) {
        reg.register_json_any(super::__CHAINS_REQUEST_JSON_ANY);
        reg.register_json_any(super::__CHAINS_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__CHAIN_JSON_ANY);
        reg.register_json_any(super::__TRC_REQUEST_JSON_ANY);
        reg.register_json_any(super::__TRC_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__VERIFICATION_KEY_ID_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_SECRET_VALUE_REQUEST_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_SECRET_VALUE_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_LEVEL1REQUEST_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_LEVEL1RESPONSE_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_INTRA_LEVEL1REQUEST_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_INTRA_LEVEL1RESPONSE_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_HOST_AS_REQUEST_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_HOST_AS_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_AS_HOST_REQUEST_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_AS_HOST_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_HOST_HOST_REQUEST_JSON_ANY);
        reg.register_json_any(super::__DR_KEY_HOST_HOST_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__CHAIN_RENEWAL_REQUEST_JSON_ANY);
        reg.register_json_any(super::__CHAIN_RENEWAL_REQUEST_BODY_JSON_ANY);
        reg.register_json_any(super::__CHAIN_RENEWAL_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__CHAIN_RENEWAL_RESPONSE_BODY_JSON_ANY);
        reg.register_json_any(super::__SEGMENTS_REQUEST_JSON_ANY);
        reg.register_json_any(super::__SEGMENTS_RESPONSE_JSON_ANY);
        reg.register_json_any(super::segments_response::__SEGMENTS_JSON_ANY);
        reg.register_json_any(super::__SEGMENTS_REGISTRATION_REQUEST_JSON_ANY);
        reg.register_json_any(super::segments_registration_request::__SEGMENTS_JSON_ANY);
        reg.register_json_any(super::__SEGMENTS_REGISTRATION_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__BEACON_REQUEST_JSON_ANY);
        reg.register_json_any(super::__BEACON_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__PATH_SEGMENT_JSON_ANY);
        reg.register_json_any(super::__SEGMENT_INFORMATION_JSON_ANY);
        reg.register_json_any(super::__AS_ENTRY_JSON_ANY);
        reg.register_json_any(super::__AS_ENTRY_SIGNED_BODY_JSON_ANY);
        reg.register_json_any(super::__HOP_ENTRY_JSON_ANY);
        reg.register_json_any(super::__PEER_ENTRY_JSON_ANY);
        reg.register_json_any(super::__HOP_FIELD_JSON_ANY);
        reg.register_json_any(super::__PATH_SEGMENT_EXTENSIONS_JSON_ANY);
        reg.register_json_any(super::__HIDDEN_PATH_EXTENSION_JSON_ANY);
        reg.register_json_any(super::__STATIC_INFO_EXTENSION_JSON_ANY);
        reg.register_json_any(super::__LATENCY_INFO_JSON_ANY);
        reg.register_json_any(super::__BANDWIDTH_INFO_JSON_ANY);
        reg.register_json_any(super::__GEO_COORDINATES_JSON_ANY);
        reg.register_json_any(super::__DIGEST_EXTENSION_JSON_ANY);
        reg.register_json_any(super::digest_extension::__DIGEST_JSON_ANY);
        reg.register_json_any(super::__PATH_SEGMENT_UNSIGNED_EXTENSIONS_JSON_ANY);
        reg.register_json_any(super::__SERVICE_RESOLUTION_REQUEST_JSON_ANY);
        reg.register_json_any(super::__SERVICE_RESOLUTION_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__TRANSPORT_JSON_ANY);
    }
}
#[doc(inline)]
pub use self::__buffa::view::ChainsRequestView;
#[doc(inline)]
pub use self::__buffa::view::ChainsRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ChainsResponseView;
#[doc(inline)]
pub use self::__buffa::view::ChainsResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ChainView;
#[doc(inline)]
pub use self::__buffa::view::ChainOwnedView;
#[doc(inline)]
pub use self::__buffa::view::TRCRequestView;
#[doc(inline)]
pub use self::__buffa::view::TRCRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::TRCResponseView;
#[doc(inline)]
pub use self::__buffa::view::TRCResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::VerificationKeyIDView;
#[doc(inline)]
pub use self::__buffa::view::VerificationKeyIDOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeySecretValueRequestView;
#[doc(inline)]
pub use self::__buffa::view::DRKeySecretValueRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeySecretValueResponseView;
#[doc(inline)]
pub use self::__buffa::view::DRKeySecretValueResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyLevel1RequestView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyLevel1RequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyLevel1ResponseView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyLevel1ResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyIntraLevel1RequestView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyIntraLevel1RequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyIntraLevel1ResponseView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyIntraLevel1ResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyHostASRequestView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyHostASRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyHostASResponseView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyHostASResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyASHostRequestView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyASHostRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyASHostResponseView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyASHostResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyHostHostRequestView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyHostHostRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyHostHostResponseView;
#[doc(inline)]
pub use self::__buffa::view::DRKeyHostHostResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ChainRenewalRequestView;
#[doc(inline)]
pub use self::__buffa::view::ChainRenewalRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ChainRenewalRequestBodyView;
#[doc(inline)]
pub use self::__buffa::view::ChainRenewalRequestBodyOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ChainRenewalResponseView;
#[doc(inline)]
pub use self::__buffa::view::ChainRenewalResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ChainRenewalResponseBodyView;
#[doc(inline)]
pub use self::__buffa::view::ChainRenewalResponseBodyOwnedView;
#[doc(inline)]
pub use self::__buffa::view::SegmentsRequestView;
#[doc(inline)]
pub use self::__buffa::view::SegmentsRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::SegmentsResponseView;
#[doc(inline)]
pub use self::__buffa::view::SegmentsResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::SegmentsRegistrationRequestView;
#[doc(inline)]
pub use self::__buffa::view::SegmentsRegistrationRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::SegmentsRegistrationResponseView;
#[doc(inline)]
pub use self::__buffa::view::SegmentsRegistrationResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::BeaconRequestView;
#[doc(inline)]
pub use self::__buffa::view::BeaconRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::BeaconResponseView;
#[doc(inline)]
pub use self::__buffa::view::BeaconResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::PathSegmentView;
#[doc(inline)]
pub use self::__buffa::view::PathSegmentOwnedView;
#[doc(inline)]
pub use self::__buffa::view::SegmentInformationView;
#[doc(inline)]
pub use self::__buffa::view::SegmentInformationOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ASEntryView;
#[doc(inline)]
pub use self::__buffa::view::ASEntryOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ASEntrySignedBodyView;
#[doc(inline)]
pub use self::__buffa::view::ASEntrySignedBodyOwnedView;
#[doc(inline)]
pub use self::__buffa::view::HopEntryView;
#[doc(inline)]
pub use self::__buffa::view::HopEntryOwnedView;
#[doc(inline)]
pub use self::__buffa::view::PeerEntryView;
#[doc(inline)]
pub use self::__buffa::view::PeerEntryOwnedView;
#[doc(inline)]
pub use self::__buffa::view::HopFieldView;
#[doc(inline)]
pub use self::__buffa::view::HopFieldOwnedView;
#[doc(inline)]
pub use self::__buffa::view::PathSegmentExtensionsView;
#[doc(inline)]
pub use self::__buffa::view::PathSegmentExtensionsOwnedView;
#[doc(inline)]
pub use self::__buffa::view::HiddenPathExtensionView;
#[doc(inline)]
pub use self::__buffa::view::HiddenPathExtensionOwnedView;
#[doc(inline)]
pub use self::__buffa::view::StaticInfoExtensionView;
#[doc(inline)]
pub use self::__buffa::view::StaticInfoExtensionOwnedView;
#[doc(inline)]
pub use self::__buffa::view::LatencyInfoView;
#[doc(inline)]
pub use self::__buffa::view::LatencyInfoOwnedView;
#[doc(inline)]
pub use self::__buffa::view::BandwidthInfoView;
#[doc(inline)]
pub use self::__buffa::view::BandwidthInfoOwnedView;
#[doc(inline)]
pub use self::__buffa::view::GeoCoordinatesView;
#[doc(inline)]
pub use self::__buffa::view::GeoCoordinatesOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DigestExtensionView;
#[doc(inline)]
pub use self::__buffa::view::DigestExtensionOwnedView;
#[doc(inline)]
pub use self::__buffa::view::PathSegmentUnsignedExtensionsView;
#[doc(inline)]
pub use self::__buffa::view::PathSegmentUnsignedExtensionsOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ServiceResolutionRequestView;
#[doc(inline)]
pub use self::__buffa::view::ServiceResolutionRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ServiceResolutionResponseView;
#[doc(inline)]
pub use self::__buffa::view::ServiceResolutionResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::TransportView;
#[doc(inline)]
pub use self::__buffa::view::TransportOwnedView;
#[doc(inline)]
pub use self::__buffa::register_types;
include!("proto.control_plane.v1.cppki.__connect.rs");
include!("proto.control_plane.v1.drkey.__connect.rs");
include!("proto.control_plane.v1.renewal.__connect.rs");
include!("proto.control_plane.v1.seg.__connect.rs");
