// @generated by buffa-codegen. DO NOT EDIT.
// source: proto/crypto/v1/signed.proto

#[derive(Clone, Debug, Default)]
pub struct SignedMessageView<'a> {
    /// Field 1: `header_and_body`
    pub header_and_body: &'a [u8],
    /// Field 2: `signature`
    pub signature: &'a [u8],
}
impl<'a> ::buffa::MessageView<'a> for SignedMessageView<'a> {
    type Owned = super::super::SignedMessage;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.header_and_body = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.signature = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::SignedMessage, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::SignedMessage, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::SignedMessage {
            header_and_body: (self.header_and_body).to_vec(),
            signature: (self.signature).to_vec(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for SignedMessageView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.header_and_body.is_empty() {
            size
                += 1u32
                    + ::buffa::types::bytes_encoded_len(&self.header_and_body) as u32;
        }
        if !self.signature.is_empty() {
            size += 1u32 + ::buffa::types::bytes_encoded_len(&self.signature) as u32;
        }
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.header_and_body.is_empty() {
            ::buffa::types::put_bytes_field(1u32, &self.header_and_body, buf);
        }
        if !self.signature.is_empty() {
            ::buffa::types::put_bytes_field(2u32, &self.signature, buf);
        }
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for SignedMessageView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !::buffa::json_helpers::skip_if::is_empty_bytes(self.header_and_body) {
            __map
                .serialize_entry(
                    "headerAndBody",
                    &::buffa::json_helpers::BytesJson(self.header_and_body),
                )?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_bytes(self.signature) {
            __map
                .serialize_entry(
                    "signature",
                    &::buffa::json_helpers::BytesJson(self.signature),
                )?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for SignedMessageView<'a> {
    const PACKAGE: &'static str = "proto.crypto.v1";
    const NAME: &'static str = "SignedMessage";
    const FULL_NAME: &'static str = "proto.crypto.v1.SignedMessage";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.crypto.v1.SignedMessage";
}
::buffa::impl_default_view_instance!(SignedMessageView);
::buffa::impl_view_reborrow!(SignedMessageView);
/** Self-contained, `'static` owned view of a `SignedMessage` message.

 Wraps [`::buffa::OwnedView`]`<`[`SignedMessageView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`SignedMessageView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct SignedMessageOwnedView(::buffa::OwnedView<SignedMessageView<'static>>);
impl SignedMessageOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            SignedMessageOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            SignedMessageOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::SignedMessage,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            SignedMessageOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`SignedMessageView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &SignedMessageView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::SignedMessage, ::buffa::DecodeError> {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `header_and_body`
    #[must_use]
    pub fn header_and_body(&self) -> &'_ [u8] {
        self.0.reborrow().header_and_body
    }
    /// Field 2: `signature`
    #[must_use]
    pub fn signature(&self) -> &'_ [u8] {
        self.0.reborrow().signature
    }
}
impl ::core::convert::From<::buffa::OwnedView<SignedMessageView<'static>>>
for SignedMessageOwnedView {
    fn from(inner: ::buffa::OwnedView<SignedMessageView<'static>>) -> Self {
        SignedMessageOwnedView(inner)
    }
}
impl ::core::convert::From<SignedMessageOwnedView>
for ::buffa::OwnedView<SignedMessageView<'static>> {
    fn from(wrapper: SignedMessageOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<SignedMessageView<'static>>>
for SignedMessageOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<SignedMessageView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::SignedMessage {
    type View<'a> = SignedMessageView<'a>;
    type ViewHandle = SignedMessageOwnedView;
}
impl ::serde::Serialize for SignedMessageOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
#[derive(Clone, Debug, Default)]
pub struct HeaderView<'a> {
    /// Field 1: `signature_algorithm`
    pub signature_algorithm: ::buffa::EnumValue<super::super::SignatureAlgorithm>,
    /// Field 2: `verification_key_id`
    pub verification_key_id: &'a [u8],
    /// Field 3: `timestamp`
    pub timestamp: ::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'a>,
    >,
    /// Field 4: `metadata`
    pub metadata: &'a [u8],
    /// Field 5: `associated_data_length`
    pub associated_data_length: i32,
}
impl<'a> ::buffa::MessageView<'a> for HeaderView<'a> {
    type Owned = super::super::Header;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.signature_algorithm = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(&mut cur)?,
                );
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.verification_key_id = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                match view.timestamp.as_mut() {
                    Some(existing) => {
                        ::buffa::MessageView::merge_into_view(existing, sub, __sub_ctx)?
                    }
                    None => {
                        view.timestamp = ::buffa::MessageFieldView::set(
                            <::buffa_types::google::protobuf::__buffa::view::TimestampView as ::buffa::MessageView>::decode_view_ctx(
                                sub,
                                __sub_ctx,
                            )?,
                        );
                    }
                }
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.metadata = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.associated_data_length = ::buffa::types::decode_int32(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Header, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Header, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Header {
            signature_algorithm: self.signature_algorithm,
            verification_key_id: (self.verification_key_id).to_vec(),
            timestamp: match self.timestamp.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        ::buffa_types::google::protobuf::Timestamp,
                    >::some(v.to_owned_from_source(__buffa_src)?)
                }
                None => ::buffa::MessageField::none(),
            },
            metadata: (self.metadata).to_vec(),
            associated_data_length: self.associated_data_length,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for HeaderView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        {
            let val = self.signature_algorithm.to_i32();
            if val != 0 {
                size += 1u32 + ::buffa::types::int32_encoded_len(val) as u32;
            }
        }
        if !self.verification_key_id.is_empty() {
            size
                += 1u32
                    + ::buffa::types::bytes_encoded_len(&self.verification_key_id)
                        as u32;
        }
        if self.timestamp.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.timestamp.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        if !self.metadata.is_empty() {
            size += 1u32 + ::buffa::types::bytes_encoded_len(&self.metadata) as u32;
        }
        if self.associated_data_length != 0i32 {
            size
                += 1u32
                    + ::buffa::types::int32_encoded_len(self.associated_data_length)
                        as u32;
        }
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        {
            let val = self.signature_algorithm.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(1u32, val, buf);
            }
        }
        if !self.verification_key_id.is_empty() {
            ::buffa::types::put_bytes_field(2u32, &self.verification_key_id, buf);
        }
        if self.timestamp.is_set() {
            ::buffa::types::put_len_delimited_header(3u32, __cache.consume_next(), buf);
            self.timestamp.write_to(__cache, buf);
        }
        if !self.metadata.is_empty() {
            ::buffa::types::put_bytes_field(4u32, &self.metadata, buf);
        }
        if self.associated_data_length != 0i32 {
            ::buffa::types::put_int32_field(5u32, self.associated_data_length, buf);
        }
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for HeaderView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !::buffa::json_helpers::skip_if::is_default_enum_value(
            &self.signature_algorithm,
        ) {
            __map.serialize_entry("signatureAlgorithm", &self.signature_algorithm)?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_bytes(self.verification_key_id) {
            __map
                .serialize_entry(
                    "verificationKeyId",
                    &::buffa::json_helpers::BytesJson(self.verification_key_id),
                )?;
        }
        {
            if let ::core::option::Option::Some(__v) = self.timestamp.as_option() {
                __map.serialize_entry("timestamp", __v)?;
            }
        }
        if !::buffa::json_helpers::skip_if::is_empty_bytes(self.metadata) {
            __map
                .serialize_entry(
                    "metadata",
                    &::buffa::json_helpers::BytesJson(self.metadata),
                )?;
        }
        if !::buffa::json_helpers::skip_if::is_zero_i32(&self.associated_data_length) {
            __map
                .serialize_entry(
                    "associatedDataLength",
                    &::buffa::json_helpers::ProtoJson(&self.associated_data_length),
                )?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for HeaderView<'a> {
    const PACKAGE: &'static str = "proto.crypto.v1";
    const NAME: &'static str = "Header";
    const FULL_NAME: &'static str = "proto.crypto.v1.Header";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.crypto.v1.Header";
}
::buffa::impl_default_view_instance!(HeaderView);
::buffa::impl_view_reborrow!(HeaderView);
/** Self-contained, `'static` owned view of a `Header` message.

 Wraps [`::buffa::OwnedView`]`<`[`HeaderView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`HeaderView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct HeaderOwnedView(::buffa::OwnedView<HeaderView<'static>>);
impl HeaderOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(HeaderOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HeaderOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Header,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(HeaderOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`HeaderView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &HeaderView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Header, ::buffa::DecodeError> {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `signature_algorithm`
    #[must_use]
    pub fn signature_algorithm(
        &self,
    ) -> ::buffa::EnumValue<super::super::SignatureAlgorithm> {
        self.0.reborrow().signature_algorithm
    }
    /// Field 2: `verification_key_id`
    #[must_use]
    pub fn verification_key_id(&self) -> &'_ [u8] {
        self.0.reborrow().verification_key_id
    }
    /// Field 3: `timestamp`
    #[must_use]
    pub fn timestamp(
        &self,
    ) -> &::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'_>,
    > {
        &self.0.reborrow().timestamp
    }
    /// Field 4: `metadata`
    #[must_use]
    pub fn metadata(&self) -> &'_ [u8] {
        self.0.reborrow().metadata
    }
    /// Field 5: `associated_data_length`
    #[must_use]
    pub fn associated_data_length(&self) -> i32 {
        self.0.reborrow().associated_data_length
    }
}
impl ::core::convert::From<::buffa::OwnedView<HeaderView<'static>>> for HeaderOwnedView {
    fn from(inner: ::buffa::OwnedView<HeaderView<'static>>) -> Self {
        HeaderOwnedView(inner)
    }
}
impl ::core::convert::From<HeaderOwnedView> for ::buffa::OwnedView<HeaderView<'static>> {
    fn from(wrapper: HeaderOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<HeaderView<'static>>>
for HeaderOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<HeaderView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Header {
    type View<'a> = HeaderView<'a>;
    type ViewHandle = HeaderOwnedView;
}
impl ::serde::Serialize for HeaderOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
#[derive(Clone, Debug, Default)]
pub struct HeaderAndBodyInternalView<'a> {
    /// Field 1: `header`
    pub header: &'a [u8],
    /// Field 2: `body`
    pub body: &'a [u8],
}
impl<'a> ::buffa::MessageView<'a> for HeaderAndBodyInternalView<'a> {
    type Owned = super::super::HeaderAndBodyInternal;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.header = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.body = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::HeaderAndBodyInternal,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::HeaderAndBodyInternal,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::HeaderAndBodyInternal {
            header: (self.header).to_vec(),
            body: (self.body).to_vec(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for HeaderAndBodyInternalView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.header.is_empty() {
            size += 1u32 + ::buffa::types::bytes_encoded_len(&self.header) as u32;
        }
        if !self.body.is_empty() {
            size += 1u32 + ::buffa::types::bytes_encoded_len(&self.body) as u32;
        }
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.header.is_empty() {
            ::buffa::types::put_bytes_field(1u32, &self.header, buf);
        }
        if !self.body.is_empty() {
            ::buffa::types::put_bytes_field(2u32, &self.body, buf);
        }
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for HeaderAndBodyInternalView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !::buffa::json_helpers::skip_if::is_empty_bytes(self.header) {
            __map
                .serialize_entry(
                    "header",
                    &::buffa::json_helpers::BytesJson(self.header),
                )?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_bytes(self.body) {
            __map.serialize_entry("body", &::buffa::json_helpers::BytesJson(self.body))?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for HeaderAndBodyInternalView<'a> {
    const PACKAGE: &'static str = "proto.crypto.v1";
    const NAME: &'static str = "HeaderAndBodyInternal";
    const FULL_NAME: &'static str = "proto.crypto.v1.HeaderAndBodyInternal";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.crypto.v1.HeaderAndBodyInternal";
}
::buffa::impl_default_view_instance!(HeaderAndBodyInternalView);
::buffa::impl_view_reborrow!(HeaderAndBodyInternalView);
/** Self-contained, `'static` owned view of a `HeaderAndBodyInternal` message.

 Wraps [`::buffa::OwnedView`]`<`[`HeaderAndBodyInternalView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`HeaderAndBodyInternalView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct HeaderAndBodyInternalOwnedView(
    ::buffa::OwnedView<HeaderAndBodyInternalView<'static>>,
);
impl HeaderAndBodyInternalOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HeaderAndBodyInternalOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HeaderAndBodyInternalOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::HeaderAndBodyInternal,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HeaderAndBodyInternalOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`HeaderAndBodyInternalView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &HeaderAndBodyInternalView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::HeaderAndBodyInternal,
        ::buffa::DecodeError,
    > {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `header`
    #[must_use]
    pub fn header(&self) -> &'_ [u8] {
        self.0.reborrow().header
    }
    /// Field 2: `body`
    #[must_use]
    pub fn body(&self) -> &'_ [u8] {
        self.0.reborrow().body
    }
}
impl ::core::convert::From<::buffa::OwnedView<HeaderAndBodyInternalView<'static>>>
for HeaderAndBodyInternalOwnedView {
    fn from(inner: ::buffa::OwnedView<HeaderAndBodyInternalView<'static>>) -> Self {
        HeaderAndBodyInternalOwnedView(inner)
    }
}
impl ::core::convert::From<HeaderAndBodyInternalOwnedView>
for ::buffa::OwnedView<HeaderAndBodyInternalView<'static>> {
    fn from(wrapper: HeaderAndBodyInternalOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<HeaderAndBodyInternalView<'static>>>
for HeaderAndBodyInternalOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<HeaderAndBodyInternalView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::HeaderAndBodyInternal {
    type View<'a> = HeaderAndBodyInternalView<'a>;
    type ViewHandle = HeaderAndBodyInternalOwnedView;
}
impl ::serde::Serialize for HeaderAndBodyInternalOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
