// @generated by buffa-codegen. DO NOT EDIT.
// source: proto/control_plane/v1/svc_resolution.proto

#[derive(Clone, Debug, Default)]
pub struct ServiceResolutionRequestView<'a> {
    #[doc(hidden)]
    pub __buffa_phantom: ::core::marker::PhantomData<&'a ()>,
}
impl<'a> ::buffa::MessageView<'a> for ServiceResolutionRequestView<'a> {
    type Owned = super::super::ServiceResolutionRequest;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::ServiceResolutionRequest,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::ServiceResolutionRequest,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::ServiceResolutionRequest {
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for ServiceResolutionRequestView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let size = 0u32;
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        _buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for ServiceResolutionRequestView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for ServiceResolutionRequestView<'a> {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "ServiceResolutionRequest";
    const FULL_NAME: &'static str = "proto.control_plane.v1.ServiceResolutionRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.ServiceResolutionRequest";
}
::buffa::impl_default_view_instance!(ServiceResolutionRequestView);
::buffa::impl_view_reborrow!(ServiceResolutionRequestView);
/** Self-contained, `'static` owned view of a `ServiceResolutionRequest` message.

 Wraps [`::buffa::OwnedView`]`<`[`ServiceResolutionRequestView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`ServiceResolutionRequestView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct ServiceResolutionRequestOwnedView(
    ::buffa::OwnedView<ServiceResolutionRequestView<'static>>,
);
impl ServiceResolutionRequestOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ServiceResolutionRequestOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ServiceResolutionRequestOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::ServiceResolutionRequest,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ServiceResolutionRequestOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`ServiceResolutionRequestView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &ServiceResolutionRequestView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::ServiceResolutionRequest,
        ::buffa::DecodeError,
    > {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
}
impl ::core::convert::From<::buffa::OwnedView<ServiceResolutionRequestView<'static>>>
for ServiceResolutionRequestOwnedView {
    fn from(inner: ::buffa::OwnedView<ServiceResolutionRequestView<'static>>) -> Self {
        ServiceResolutionRequestOwnedView(inner)
    }
}
impl ::core::convert::From<ServiceResolutionRequestOwnedView>
for ::buffa::OwnedView<ServiceResolutionRequestView<'static>> {
    fn from(wrapper: ServiceResolutionRequestOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<ServiceResolutionRequestView<'static>>>
for ServiceResolutionRequestOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<ServiceResolutionRequestView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::ServiceResolutionRequest {
    type View<'a> = ServiceResolutionRequestView<'a>;
    type ViewHandle = ServiceResolutionRequestOwnedView;
}
impl ::serde::Serialize for ServiceResolutionRequestOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
#[derive(Clone, Debug, Default)]
pub struct ServiceResolutionResponseView<'a> {
    /// Field 1: `transports` (map)
    pub transports: ::buffa::MapView<
        'a,
        &'a str,
        super::super::__buffa::view::TransportView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for ServiceResolutionResponseView<'a> {
    type Owned = super::super::ServiceResolutionResponse;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let entry_bytes = ::buffa::types::borrow_bytes(&mut cur)?;
                let mut entry_cur: &'a [u8] = entry_bytes;
                let mut key = "";
                let mut val = ::core::default::Default::default();
                while !entry_cur.is_empty() {
                    let entry_tag = ::buffa::encoding::Tag::decode(&mut entry_cur)?;
                    match entry_tag.field_number() {
                        1 => {
                            ::buffa::encoding::check_wire_type(
                                entry_tag,
                                ::buffa::encoding::WireType::LengthDelimited,
                            )?;
                            key = ::buffa::types::borrow_str(&mut entry_cur)?;
                        }
                        2 => {
                            ::buffa::encoding::check_wire_type(
                                entry_tag,
                                ::buffa::encoding::WireType::LengthDelimited,
                            )?;
                            let __sub_ctx = ctx.descend()?;
                            let sub = ::buffa::types::borrow_bytes(&mut entry_cur)?;
                            val = <super::super::__buffa::view::TransportView as ::buffa::MessageView>::decode_view_ctx(
                                sub,
                                __sub_ctx,
                            )?;
                        }
                        _ => {
                            ::buffa::encoding::skip_field_depth(
                                entry_tag,
                                &mut entry_cur,
                                ctx.depth(),
                            )?;
                        }
                    }
                }
                view.transports.push(key, val);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::ServiceResolutionResponse,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::ServiceResolutionResponse,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::ServiceResolutionResponse {
            transports: self
                .transports
                .iter()
                .map(|(k, v)| {
                    ::core::result::Result::<
                        _,
                        ::buffa::DecodeError,
                    >::Ok((k.to_string(), v.to_owned_from_source(__buffa_src)?))
                })
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for ServiceResolutionResponseView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        #[allow(clippy::for_kv_map)]
        for (k, v) in &self.transports {
            let entry_size: u32 = 1u32 + ::buffa::types::string_encoded_len(k) as u32
                + 1u32
                + {
                    let __slot = __cache.reserve();
                    let inner = v.compute_size(__cache);
                    __cache.set(__slot, inner);
                    ::buffa::encoding::varint_len(inner as u64) as u32 + inner
                };
            size
                += 1u32 + ::buffa::encoding::varint_len(entry_size as u64) as u32
                    + entry_size;
        }
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for (k, v) in &self.transports {
            let __v_len = __cache.consume_next();
            let entry_size: u32 = 1u32 + ::buffa::types::string_encoded_len(k) as u32
                + 1u32
                + (::buffa::encoding::varint_len(__v_len as u64) as u32 + __v_len);
            ::buffa::encoding::Tag::new(
                    1u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(entry_size as u64, buf);
            ::buffa::encoding::Tag::new(
                    1u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(k, buf);
            ::buffa::encoding::Tag::new(
                    2u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(__v_len as u64, buf);
            v.write_to(__cache, buf);
        }
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for ServiceResolutionResponseView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !self.transports.is_empty() {
            struct _WM<'__a, '__x>(
                &'__x ::buffa::MapView<
                    '__x,
                    &'__a str,
                    super::super::__buffa::view::TransportView<'__a>,
                >,
            );
            impl<'__a> ::serde::Serialize for _WM<'__a, '_> {
                fn serialize<__S: ::serde::Serializer>(
                    &self,
                    __s: __S,
                ) -> ::core::result::Result<__S::Ok, __S::Error> {
                    use ::serde::ser::SerializeMap as _;
                    let mut __m = __s
                        .serialize_map(::core::option::Option::Some(self.0.len()))?;
                    for (k, v) in self.0.iter_unique() {
                        __m.serialize_entry(k, v)?;
                    }
                    __m.end()
                }
            }
            __map.serialize_entry("transports", &_WM(&self.transports))?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for ServiceResolutionResponseView<'a> {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "ServiceResolutionResponse";
    const FULL_NAME: &'static str = "proto.control_plane.v1.ServiceResolutionResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.ServiceResolutionResponse";
}
::buffa::impl_default_view_instance!(ServiceResolutionResponseView);
::buffa::impl_view_reborrow!(ServiceResolutionResponseView);
/** Self-contained, `'static` owned view of a `ServiceResolutionResponse` message.

 Wraps [`::buffa::OwnedView`]`<`[`ServiceResolutionResponseView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`ServiceResolutionResponseView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct ServiceResolutionResponseOwnedView(
    ::buffa::OwnedView<ServiceResolutionResponseView<'static>>,
);
impl ServiceResolutionResponseOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ServiceResolutionResponseOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ServiceResolutionResponseOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::ServiceResolutionResponse,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ServiceResolutionResponseOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`ServiceResolutionResponseView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &ServiceResolutionResponseView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::ServiceResolutionResponse,
        ::buffa::DecodeError,
    > {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `transports` (map)
    #[must_use]
    pub fn transports(
        &self,
    ) -> &::buffa::MapView<'_, &'_ str, super::super::__buffa::view::TransportView<'_>> {
        &self.0.reborrow().transports
    }
}
impl ::core::convert::From<::buffa::OwnedView<ServiceResolutionResponseView<'static>>>
for ServiceResolutionResponseOwnedView {
    fn from(inner: ::buffa::OwnedView<ServiceResolutionResponseView<'static>>) -> Self {
        ServiceResolutionResponseOwnedView(inner)
    }
}
impl ::core::convert::From<ServiceResolutionResponseOwnedView>
for ::buffa::OwnedView<ServiceResolutionResponseView<'static>> {
    fn from(wrapper: ServiceResolutionResponseOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<ServiceResolutionResponseView<'static>>>
for ServiceResolutionResponseOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<ServiceResolutionResponseView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::ServiceResolutionResponse {
    type View<'a> = ServiceResolutionResponseView<'a>;
    type ViewHandle = ServiceResolutionResponseOwnedView;
}
impl ::serde::Serialize for ServiceResolutionResponseOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
#[derive(Clone, Debug, Default)]
pub struct TransportView<'a> {
    /// Field 1: `address`
    pub address: &'a str,
}
impl<'a> ::buffa::MessageView<'a> for TransportView<'a> {
    type Owned = super::super::Transport;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.address = ::buffa::types::borrow_str(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Transport, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Transport, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Transport {
            address: self.address.to_string(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for TransportView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.address.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.address) as u32;
        }
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.address.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.address, buf);
        }
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for TransportView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !::buffa::json_helpers::skip_if::is_empty_str(self.address) {
            __map.serialize_entry("address", self.address)?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for TransportView<'a> {
    const PACKAGE: &'static str = "proto.control_plane.v1";
    const NAME: &'static str = "Transport";
    const FULL_NAME: &'static str = "proto.control_plane.v1.Transport";
    const TYPE_URL: &'static str = "type.googleapis.com/proto.control_plane.v1.Transport";
}
::buffa::impl_default_view_instance!(TransportView);
::buffa::impl_view_reborrow!(TransportView);
/** Self-contained, `'static` owned view of a `Transport` message.

 Wraps [`::buffa::OwnedView`]`<`[`TransportView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`TransportView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct TransportOwnedView(::buffa::OwnedView<TransportView<'static>>);
impl TransportOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            TransportOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            TransportOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Transport,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            TransportOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`TransportView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &TransportView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// # Errors
    ///
    /// Returns an error if re-materializing preserved unknown fields
    /// fails (e.g. the unknown-field limit is exceeded).
    pub fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Transport, ::buffa::DecodeError> {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `address`
    #[must_use]
    pub fn address(&self) -> &'_ str {
        self.0.reborrow().address
    }
}
impl ::core::convert::From<::buffa::OwnedView<TransportView<'static>>>
for TransportOwnedView {
    fn from(inner: ::buffa::OwnedView<TransportView<'static>>) -> Self {
        TransportOwnedView(inner)
    }
}
impl ::core::convert::From<TransportOwnedView>
for ::buffa::OwnedView<TransportView<'static>> {
    fn from(wrapper: TransportOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<TransportView<'static>>>
for TransportOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<TransportView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Transport {
    type View<'a> = TransportView<'a>;
    type ViewHandle = TransportOwnedView;
}
impl ::serde::Serialize for TransportOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
