[package]
name = "proto-gen"
edition.workspace = true
publish = false
license = "Apache-2.0"
description = "A tool to compile all protobuf definitions to Rust code"
repository = "https://github.com/anapaya/scion-sdk"

[package.metadata.release]
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }

buffa-build = "0.8"
connectrpc-build = "0.8"

tempfile = { workspace = true }
walkdir = { workspace = true }

[lints]
workspace = true
